### ISSUE TITLE
Multiple Postgres to S3 Backup Schedules

### ISSUE THREAD

**Issue by bradbajuz** [dokku/dokku-postgres#101]
I'm having an issue setting two postgres backup schedules for S3 offsite backups for two different databases.

One of the scheduled backups works, the other scheduled backup doesn't work. Manual backup works fine.

1. Is there anyway to view the cron jobs for each of the backups?
2. Where are the cron jobs and S3 authentication credentials stored?

**Comment by josegonzalez** [comment]
We only create a single cron schedule for a given database.

1. The file is in `/etc/cron.d/dokku-${PLUGIN_COMMAND_PREFIX}-${SERVICE}`.
2. The keys are stored on disk in the service's `$SERVICE_ROOT/backup` directory.

**Comment by bradbajuz** [comment]
I have two databases each with only one cron schedule. I just removed the schedule for the backup I'm having problems with and added it back. Checked the two cron files and everything looks right for each database.

The backup jobs should run in a bit. Will update later with the status.

Thanks for you help.

**Comment by josegonzalez** [comment]
Logs should be in `/var/log/syslog`, so check there in case you are having issues.

**Comment by bradbajuz** [comment]
Everything looks like it's working now.

Issue was with the quoting around the cron expression:
`“0 */6 * * *”` - Smart Quotes (Slanted) caused an issue
`"0 */6 * * *"` - Dumb Quotes (Straight) worked

The smart quotes are caused from formatting in rich text editors, Notes (my case) or other word processors.

**Comment by josegonzalez** [comment]
Gotcha :)
