### ISSUE TITLE
postgres (without command like :info) should behave like apps and do :list command

### ISSUE THREAD

**Issue by fwolfst** [dokku/dokku-postgres#102]
When called without arguments (`dokku postgres`), the plugin "fails" (exits with 1). In contrast, `dokku apps` outputs the list of installed apps. postgres should do the same (~~and `apps` should implement `apps:list`, imho - should I file a separate issue for that?~~ (implemented 12 days ago...)).

```
dokku postgres
 !     `postgres` is not a dokku command.
 !     See `dokku help` for a list of available commands.

```

**Comment by fwolfst** [comment]
I am not sure whether I still support the wording of that issue - imho behaviour should be consistent across commands but I am not sure what the default behaviour should be. I am only a casual user only, so I'd love to see this in the documentation (and implemented) to get it into my cmd-muscles memory.

Basically, there are three options:

1) If the command is about entities, default to a `:list`-like command - `dokku apps` (an dplugin) behaves like this as of dokku 0.8
2) Default to `:help` - tbh this would be my preferred solution, but as said this might be motivated by the fact that unfortunately I dont have to use dokku everyday. Anyway it would be very friedly towards casual users.
3) Unpredictable :) - like it is now.

Obviously, not all commands can behave the same way (one-off commands like `:version` or `:help` probably shouldnt), but for the "entity-related" commands like `postgres`, `storage`, `apps`, `plugin`(s?), `certs`, ... 

The more I think of it, the more I'd like the "entity-type" commands to respond with help, if no subcommand is given and implement a `:list` subcommand.

On a different track, any `dokku command:` (note the colon) fails. And dokkumentation is misleading in some cases:

    dokku certs
     !     `certs` is not a dokku command.
     !     See `dokku help` for a list of available commands.

where `dokku help` lists `certs` as **command**.

Should I open three issues on the main dokku repo for that? (1: "Missing API-convention: output of command without subcommand", 2) Command with trailing colon misbehaves, 3) [is like 1) if already agreed on implementation of `:help` as preferred default subcommand] , otherwise 'revisit _not a dokku command'_.

**Comment by josegonzalez** [comment]
In the core, we are moving to the default command being an alias for the `help` subcommand. There are some where it's already a pseudo-report command, or alias for info.

The next release will fix the `dokku help` output and implement help as the default wherever there is no current default subcommand for a core plugin. When we already have a default subcommand that doesn't make sense - `config` is an example where it might -  I've marked it as deprecated and will remove them in favor of a help alias whenever we do a 1.0.0.

**Comment by fwolfst** [comment]
Sounds like a good plan. I assume this will land in usage and plugin development style guide and this issue can be closed for now - to resurface when API changes stabilize. Thanks.
