### ISSUE TITLE
Best approach to edit PG conf files?

### ISSUE THREAD

**Issue by joshco** [dokku/dokku-postgres#103]
What's the right approach to edit the postgres server *.conf files?
Eg, if I want to change the work_mem or connection limits.

**Comment by josegonzalez** [comment]
`dokku postgres:info SERVICE` will show the config file path for the service. You can modify them at will and restart your service as necessary.

**Comment by joshco** [comment]
The config directory is empty.  But it turns out the config files are in the data directory.

**Comment by josegonzalez** [comment]
Got it. Worth documenting.

**Comment by joshmanders** [comment]
> Worth documenting.

PR's welcome. :)

**Comment by joshco** [comment]
Done. :)
