### ISSUE TITLE
S3 bucket backup wrong region

### ISSUE THREAD

**Issue by pythdasch** [dokku/dokku-postgres#107]
Hi,

I cannot setup the backup auth because it's not a us-east-1 bucket

here is the error message : gof3r error: 400: "The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'"

I think maybe it would be good to add the config region in the plugin
thanks in advance

**Comment by josegonzalez** [comment]
Note: https://github.com/dokku/dokku-postgres#backups

But also, someone recently sponsored this work, so it should be fine? Try updating to latest master of the plugin and seeing if the error still occurs.

**Comment by pythdasch** [comment]
@josegonzalez ok thanks :)
