### ISSUE TITLE
"gof3r error…"  during postgres:backup

### ISSUE THREAD

**Issue by saneef** [dokku/dokku-postgres#109]
I'm trying to backup for the first time.

I created a S3 bucket in region 'us-east-1. But when I run 'postgres:backup' I'm getting this error

```
/bin/tar: Removing leading `/' from member names
gof3r error: Post https://my-bucket-name.s3-us-east-1x-amz-request-id.amazonaws.com/postgres-get-better-luck-db-2017-04-13-07-05-12.tgz?uploads=: dial tcp: lookup my-bucket-name.s3-us-east-1x-amz-request-id.amazonaws.com on 8.8.8.8:53: no such host
```

Any clue where to look into? Is it because of some setting in AWS or with the plug itself?

**Comment by josegonzalez** [comment]
Can you run this in trace mode?

**Comment by saneef** [comment]
Here is the trace https://gist.github.com/saneef/3b5374d1ca7af84e07032034ca323794

Replace keys and passwords

**Comment by joshrendek** [comment]
Running into this same issue

**Comment by josegonzalez** [comment]
Just pushed a fix, do you mind updating your postgres plugin and checking it out?

**Comment by joshrendek** [comment]
Working now after updating, thanks for the quick turn around 👍

**Comment by saneef** [comment]
@josegonzalez Working! Thanks for the quick the response
