### ISSUE TITLE
postgres service name and database.yml file

### ISSUE THREAD

**Issue by knzudgt** [dokku/dokku-postgres#110]
The `database.yml` file of my Ruby on Rails application contains the following record:

    production:
      <<: *default
      database: derp_app_production

Should the name of the postgres service linked to my application at Dokku match the database name in `database.yml`, so that I am expected to create the service with the following command:

    dokku postgres:create derp_app_production

Or is it possible to use a different name without raising conflicts?

    dokku postgres:create derp

**Comment by josegonzalez** [comment]
If you create a service:

```
dokku postgres:create SERVICE_NAME
```

Then the database name will be

```
SERVICE_NAME
```

Please see the documentation for further details.

**Comment by knzudgt** [comment]
@josegonzalez I understood how to assign a name to a postgres service, thank you.
However, I was mainly concerned about what name to choose and if there is any restriction.

In Ruby on Rails, the database configuration file is `config/database.yml` where each environment has its own configuration records, included the database name which is inferred by the name of the application: `application_name_environment`.
So, for the production environment we have `application_name_production`. There are also other useful records, such as the connection pool.

So I wonder: do I have to stick with the name contained in `config/database.yml` when I assign a name to the postgres service?

**Comment by josegonzalez** [comment]
We don't currently allow you to rename the postgres database that is created when you create a postgres service, so your best bet is to name it `application_name_environment` and then link appropriately.

IIRC you can just change the name in your `config/database.yml` to match the loaded service.
