### ISSUE TITLE
Docker container in restart loop

### ISSUE THREAD

**Issue by gdaunton** [dokku/dokku-postgres#116]
Hello, I recently upgraded docker to `17.05~ce` and now when I try to start my postgres processes, they all start an infinite restart loop.

I pulled the logs of the docker container and it's just continuously spitting out:
```
FATAL:  could not open directory "pg_tblspc": No such file or directory
```

versions:
- dokku: `0.10.3`
- dokku-posgres: `1.0.0`
- postgres: `9.5`

is there anyway I can recover the data from this db?

**Comment by josegonzalez** [comment]
You may wish to follow the mkdir instructions [here](https://stackoverflow.com/a/26001639/1515875). The data directory can be retrieved from `dokku postgres:info SERVICE`.
