### ISSUE TITLE
Can't unexpose port

### ISSUE THREAD

**Issue by J77J** [dokku/dokku-postgres#118]
I exposed a postgres port but now when I try to unexpose it gives an error:

[root@server ~]# dokku postgres:unexpose my_app_db
Error response from daemon: driver "overlay" failed to remove root filesystem for ******************************************************************: remove /var/lib/docker/overlay/******************************************************************/merged: device or resource busy

(strings replaced by asterisks to be on the safe side)

Now if I try to re-expose it claims that it is already exposed?

Any ideas on what I can do to fix?

thanks,

Johnny

**Comment by J77J** [comment]
OK,

had a look round and the only fix I was able to find for this error (on Centos 7) was to reboot the server (as recommended here: https://github.com/moby/moby/issues/22260), but that's obviously not ideal, so if anyone comes across a better solution....

J

**Comment by josegonzalez** [comment]
This issue was moved to dokku/dokku-redis#89
