### ISSUE TITLE
--use-iam does not seem to work

### ISSUE THREAD

**Issue by tobiasmcnulty** [dokku/dokku-postgres#120]
Passing `--use-iam` to the `postgres:backup` command just tells me to use the `--use-iam` flag:

    $ ssh dokku@my.dokku.name postgres:backup my-postgres-instance my-bucket-name --use-iam
    Provide AWS credentials or use the --use-iam flag

Which seems to be exactly what the code says to do: https://github.com/dokku/dokku-postgres/blob/15a4a0d4c106fc92d8cfc657dc4c3343562d92ca/common-functions#L115-L121

I think there's something missing here...but I'm not sure how it's intended to work.

**Comment by josegonzalez** [comment]
This issue was moved to dokku/dokku-redis#88
