### ISSUE TITLE
Backup restore issues

### ISSUE THREAD

**Issue by marcohamersma** [dokku/dokku-postgres#121]
Hey, I added database backups for my newly generated app, but I'm finding myself unable to open the files. They're not encrypted.

If I extract the .tgz file from s3 on my computer, there is a file without extension that my text editor refuses to open because it thinks it's a binary. Importing it via `psql` (`psql [database_name] < ./backup/export`) results in errors like the following: 

```
ERROR:  syntax error at or near ""
LINE 1:     ADD CONSTRAINT "menus_websiteId_fkey" FOREIGN KEY ("we...
        ^
ERROR:  syntax error at or near ""
LINE 1:     ADD CONSTRAINT "pages_websiteId_fkey" FOREIGN KEY ("we...
        ^
ERROR:  syntax error at or near ""
LINE 1:     ADD CONSTRAINT "posts_websiteId_fkey" FOREIGN KEY ("we...
        ^
ERROR:  syntax error at or near ""
LINE 1:     ADD CONSTRAINT "tasks_websiteId_fkey" FOREIGN KEY ("we...
        ^
ERROR:  syntax error at or near ""
LINE 1:     ADD CONSTRAINT "tokens_userId_fkey" FOREIGN KEY ("user...
        ^
ERROR:  syntax error at or near ""
LINE 1:     ADD CONSTRAINT "tokens_websiteId_fkey" FOREIGN KEY ("w...
        ^
ERROR:  syntax error at or near ""
LINE 1:     ADD CONSTRAINT "users_websiteId_fkey" FOREIGN KEY ("we...
        ^
ERROR:  invalid byte sequence for encoding "UTF8": 0x8d
```

I'm probably doing something I'm doing wrong, but what would be the best way to make an import into another database work, or for a text editor to open the file?

**Comment by josegonzalez** [comment]
How are you creating the backups? Can you show us the exact steps and errors you are getting?

**Comment by marcohamersma** [comment]
Sure. I mostly followed the readme, but I'm a bit insecure that everything is right because I used a different s3 region, maybe the problem is something with that?

This is basically all I did, didn't encrypt or anything:
```
dokku postgres:backup-auth bucket ID SECRET eu-central-1
dokku postgres:backup DBNAME BUCKET
```

I also scheduled a daily backup, but they haven't run yet at this point

**Comment by josegonzalez** [comment]
We actually import the backup dumpfile via `pg_restore`, not `psql`. Using that should cause your imports to start working again.
