### ISSUE TITLE
Old Postgres Databases Consuming Resources 

### ISSUE THREAD

**Issue by jal3inc** [dokku/dokku-postgres#122]
Hi, 
I am wondering if anyone has had this problem. My research has not led me to any solutions yet. I have many old pg services stuck at idle consuming resources.

Current Setup
AWS Ec2 M4.Xlarge server "4 core 16 Gb Ram"
Ubuntu 16.04 64bit / Linux 4.4.0-1032-aws
Dokku version "0.10.4"
Plugins Used: Letsencrypt, Redis, Postgres

![screen shot 2017-10-18 at 12 29 49 pm](https://user-images.githubusercontent.com/24689265/31730508-20379bec-b400-11e7-8b13-64be2fa6e5bb.png)

This is my output to 
postgres:info
postgres:list
docker container ls

![screen shot 2017-10-18 at 12 34 31 pm](https://user-images.githubusercontent.com/24689265/31730996-ae103e64-b401-11e7-91ad-9b3dcaf5bf12.png)

I have also tried manually using the dokku cleanup command to see if it would help but it did not. 
If anyone can help with a bit of guidance or maybe point me in the right direction I will greatly appreciate it. 
Thanks

**Comment by jal3inc** [comment]
![screen shot 2017-10-18 at 12 47 05 pm](https://user-images.githubusercontent.com/24689265/31731624-a68da27e-b403-11e7-9bff-c3f8b786cd31.png)

**Comment by josegonzalez** [comment]
- `dokku cleanup` only affects application containers

There are ip addresses attached to those "postgres processes". Can you `docker inspect` all your containers and see what those ip addresses correspond to?

**Comment by josegonzalez** [comment]
Closing as there hasn't been any response in a few months.
