### ISSUE TITLE
password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by dtsn** [dokku/dokku-postgres#124]
Hi,

I've been trying to wrap my head around this for ages. My app cannot connect to the Postgres database. It just gets the error `password authentication failed for user "postgres"`. I have destroyed and rebuilt both the app and the pg DB a few times to see if it was just a configuration bug.

I can connect to the DB via the `dokku postgres:connect db` command. The `process.env.DATABASE_URL` is the same DSN as is mentioned in `dokku postgres:info db`. I can even connect to the database via pgAdmin, just not through the app.

Here's my output of the `info` command:

Container Information
       Config dir:          /var/lib/dokku/services/postgres/pricehare-database/config
       Data dir:            /var/lib/dokku/services/postgres/pricehare-database/data
       Dsn:                 postgres://postgres:[password-redacted]@dokku-postgres-pricehare-database:5432/pricehare_database
       Exposed ports:       -
       Id:                  76b0f1e4bc8fe34ca79f105338aa4239d6da6063502af15c324a09f875c5067e
       Internal ip:         172.17.0.2
       Links:               pricehare
       Service root:        /var/lib/dokku/services/postgres/pricehare-database
       Status:              running
       Version:             postgres:9.6.4

**Comment by UnknownGuardian** [comment]
I've been having similar problems for quite a long time. I'm running multiple databases through dokku on this server. All of the various pg_hba.conf configurations I've tried never allow me to auth through md5.

dokku postgres:info testing
```
=====> Container Information
       Config dir:          /var/lib/dokku/services/postgres/testing/config
       Data dir:            /var/lib/dokku/services/postgres/testing/data
       Dsn:                 postgres://postgres:......@dokku-postgres-testing:5432/testing
       Exposed ports:       5432->5431
       Id:                  02f171f0dac4594d961a41cc701ab95c62a72ca109bce92240c2f0cde480c354
       Internal ip:         172.17.0.4
       Links:               testing
       Service root:        /var/lib/dokku/services/postgres/testing
       Status:              running
       Version:             postgres:9.6.4
```
My pg_hba.conf:

```

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     trust
# IPv4 local connections:
host    all             all             127.0.0.1/32            trust
# IPv6 local connections:
host    all             all             ::1/128                 trust
# Allow replication connections from localhost, by a user with the
# replication privilege.
#local   replication     postgres                                trust
#host    replication     postgres        127.0.0.1/32            trust
#host    replication     postgres        ::1/128                 trust

#host all all all md5
host testing postgres 172.17.0.5/24 md5
```

The exact error:

```
password authentication failed for user "postgres"
```

**Comment by josegonzalez** [comment]
What happens when you do:

```
dokku postgres:connect SERVICE
```

**Comment by UnknownGuardian** [comment]
Connecting through dokku works great. The app shouldn't be the issue since the `trust` auth type works great, right?

**Comment by dtsn** [comment]
@UnknownGuardian Have a look at your client which is making the connection. My problem was caused by `pg` being upgraded through NPM. I noticed a different version of my local node install and the one on the server. Once I fixed the version to the previous version and redeployed it worked.

I couldn't say what the fault was in `pg`. I could connect via every other means except through my app.

**Comment by UnknownGuardian** [comment]
Thanks @dtsn. I bumped `pq` up to 6.4.2 and everything seems to work great.

**Comment by dtsn** [comment]
@UnknownGuardian Great! I'll close this ticket and I don't think it's a problem with dokku-postgres.

**Comment by vigyhi5** [comment]
I had the similar problem..... I found my pg was 3.2.0 version and then I just changed to 6.4.2 in the package.json file and everything worked on the heroku-postgres.............Thank you for this post...I was struggling for more than a week on this.
