### ISSUE TITLE
Encrypted backups

### ISSUE THREAD

**Issue by jsuchal** [dokku/dokku-postgres#126]
Hi there,

I am having a hard time testing out the encrypted backups. Could someone give me a real world example of `postgres:backup-set-encryption <name> <encryption_key>` usage? What is the `encryption_key` format? 

Thanks in advance.

PS. Will happily update the readme in a PR once i found out. :)

**Comment by josegonzalez** [comment]
Run the following:

```
dokku postgres:help backup-set-encryption
```

**Comment by jsuchal** [comment]
I am sorry, but this is not helping me much. 

```
usage: dokku postgres:backup-set-encryption <service> <encryption-key>

sets encryption for all future backups of Postgres service

arguments:

service          service to run command against
encryption-key   a GPG encryption key

examples:

set a GPG encryption key for backups

    dokku postgres:backup-set-encryption lolipop
```
This is exactly the confusing part for me. What does the GPG encryption key look like? Do I supply it a file or a string? In what format?

**Comment by josegonzalez** [comment]
Its a string, can be anything. We pass it in as `--passphrase` to GPG [here](https://github.com/dokku/s3gof3r-docker/blob/master/backup.sh#L40).

**Comment by jsuchal** [comment]
Oh, so this is symmetric encryption with just a passphrase. I was under the (wrong) assumption that this uses public/private keys.

**Comment by josegonzalez** [comment]
Pull requests welcome.
