### ISSUE TITLE
Use a different DATABASE_URL for java applications

### ISSUE THREAD

**Issue by ezzarghili** [dokku/dokku-postgres#127]
The DATABASE_URL for the dokku postgres add-on follows the below convention
```bash
postgres://<username>:<password>@<host>:<port>/<dbname>
```
However the Postgres JDBC driver uses the following convention:
```
jdbc:postgresql://<host>:<port>/<dbname>?user=<username>&password=<password>
```

Heroku provide a second URL called JDBC_DATABASE_URL for this

**Comment by josegonzalez** [comment]
This issue was moved to dokku/dokku-redis#94
