### ISSUE TITLE
Config dir does not exist

### ISSUE THREAD

**Issue by znz** [dokku/dokku-postgres#130]
`dokku postgres:info` shows `Config dir`.
But it does not exist in newly created database dir.
I think this is since https://github.com/dokku/dokku-postgres/commit/e08854dc313be65b9e0ea121160191f347725221 .
If non-existence is expected, I think `Config dir` is unnecessary in info.

**Comment by mattdennewitz** [comment]
@josegonzalez is a missing config dir by default intended?

**Comment by josegonzalez** [comment]
It's unused.

**Comment by mattdennewitz** [comment]
@josegonzalez what's the recommended way to configure Postgres when run by this plugin?

**Comment by josegonzalez** [comment]
Just getting back to this (wow).

At the moment, probably none. If you have a suggestion as to how we can better utilize a config dir - similar to mysql - please feel free to comment. I don't know if postgres has a similar convention.

**Comment by dilame** [comment]
Seriously? No way to configure postgres?
I just faced `FATAL: sorry, too many clients already` in production... And i cant just increase max_connections?

**Comment by josegonzalez** [comment]
@dilame You need to calm down. This is an open source project and we don't owe anyone anything.

If anyone knows how to use a config dir for postgres in a similar fashion to mysql and the other datastore plugins, that would be great. I don't have time at the moment to look into this, so any help would be appreciated.

**Comment by dilame** [comment]
@josegonzalez i'm sorry if you thought I was angry. I just don't speak English very well, i didn't mean for you to owe me anything. Sorry one more time.

I can help you with this. If i `dokku:postgres enter`, all needed files located in
`/var/lib/postgresql/data`
This directory could be linked as `Config dir`

**Comment by josegonzalez** [comment]
Doesn't that already get mounted as the data-dir? I believe that is done [here](https://github.com/dokku/dokku-postgres/blob/354309feec84d61f537ffdf0891f6b7516ee0a55/functions#L82).

**Comment by dilame** [comment]
Yes, it is. I just didn't know about it. 
I think it is a bit confusing, because `Config dir` shown in `postgres:info` doesn't really exists.
Maybe it makes sense to just show the same path in both `Config dir` and `Data dir`?

**Comment by josegonzalez** [comment]
Feel free to file a pull request with that :)
