### ISSUE TITLE
SQL dump and backups

### ISSUE THREAD

**Issue by knzudgt** [dokku/dokku-postgres#132]
I would like to make backups of my postgres databases in my remote VPS and store them in my local machine. Normally I would use `pg_dumpall`, and then backup my `/` directory with borgbackup, excluding `/var/lib/postgresql/10.1/main/`. What am I required to do with `dokku-postgres`? Is the `pg_dumpall` available?

I noticed that there are two commands:
`postgres:export <name> > <file>`
`postgres:import <name> < <file>`

`pg_dump` and `pg_dumpall` do not require the database to stop and also do not block other operations on the database while it is working. Do the import and export commands behave alike?
Also, since I would exclude from my system backups the postgres data directory, where in the case of `dokku-postgres` is located the directory am I expected to exclude?

**Comment by josegonzalez** [comment]
The `export` subcommand uses `pg_dump` and the `import` subcommand uses `pg_restore` (code [here](https://github.com/dokku/dokku-postgres/blob/master/functions#L85). If you need something beyond that - like using `pg_dumpall` without dumping data and then `borgbackup` - you'll need to write a custom script to do so.

**Comment by knzudgt** [comment]
@josegonzalez thanks.
Considering that I would install dokku-postgres in a Ubuntu machine, where the database will be located (data directory)? I need this information to exclude it from my system backups. Normally on Ubuntu machines it is found in `/usr/local/pgsql/data`.

**Comment by josegonzalez** [comment]
You can get that information by using the `info` subcommand, which is documented in our readme.

**Comment by knzudgt** [comment]
@josegonzalez for large databases is it possible to use compressed dumps or alternatively write to a remote host, as follows:

`dokku postgres:export lolipop | gzip > database.dump.gz`
`dokku postgres:import lolipop < (gunzip -c database.dump.gz)`

`dokku postgres:export lolipop > sam@xxx.xxx.xxx.xxx:/media/sam/backups/database.dump`
`dokku postgres:import lolipop < sam@xxx.xxx.xxx.xxx:/media/sam/backups/database.dump`

**Comment by josegonzalez** [comment]
Probably. Did you try it?

**Comment by josegonzalez** [comment]
It should work since it just depends on stdin and stdout .
