### ISSUE TITLE
postgres:9-alpine openssl issue

### ISSUE THREAD

**Issue by litnimax** [dokku/dokku-postgres#133]
Tried to run postgres:9-alpine without success due to missing openssl binary:
```
FATAL:  could not load server certificate file "server.crt": No such file or directory
LOG:  database system is shut down
```
Here is the issue - https://github.com/dokku/dokku-postgres/blob/master/functions#L75
Manually started the image and got:
```
e9dccb3407dd:~$ openssl req -new -newkey rsa:4096 -x509 -nodes -out server.crt -keyout server.key -batch
-sh: openssl: not found
```
Seems that Alpine is missing openssl.

Also what is the sense of running SSL when all connections are local?
There must be an option (default?) to disable SSL for postgresql connections.

**Comment by josegonzalez** [comment]
This sounds like an alpine issue, not an issue with our plugin. I cannot offer support for non-standard installations. Sorry.

The "sense" is that you can expose the plugin to external connections, and also once you outgrow Dokku, you'll be secure in the future as well. We attempt to be secure by default.

**Comment by litnimax** [comment]
A very simple change is required - just test if SSL_DISABLED=1 and exit from enabled_ssh.sh script.
Because you force all have ssl db connection by default. In most cases (I am sure) the only db link is internal docker network without external access. Why waste CPU resources to encrypt all local traffic between containers?
Thanks!

**Comment by josegonzalez** [comment]
Feel free to file a PR to allow this to be optionally toggled (I'd prefer ssl by default).

**Comment by litnimax** [comment]
Ok thanks for your admission. I will.

**Comment by litnimax** [comment]
PR created.
