### ISSUE TITLE
Reset DB

### ISSUE THREAD

**Issue by fgblomqvist** [dokku/dokku-postgres#141]
Heroku has the command pg:reset that just resets a db. This is useful when e.g. cloning a DB from production to staging regularly (and automatically).
```
dokku postgres:reset staging-db
dokku postgres:export db | dokku postgres:import staging-db
```

**Comment by pynixwang** [comment]
maybe
`dokku postgres:exec 'drop schema public cascade; create schema public;'`

`exec` also can execute other command.

**Comment by fgblomqvist** [comment]
Right, the actual command required to do it right now is not very complicated. In the end, pg:reset could certainly just execute a command similar to that. I still think having the pg:reset command would just simplify things.

**Comment by pynixwang** [comment]
@fgblomqvist but `exec` command is more useful, can reset db, can run a db init script, or other awesome thing.

**Comment by fgblomqvist** [comment]
@pynixwang

Of course, but why do we even have this whole addon then? PSQL is much more useful, you can achieve every single thing with it.

You're missing my point completely.

**Comment by josegonzalez** [comment]
@fgblomqvist Would you be willing to come up with a PR for this functionality?

**Comment by fgblomqvist** [comment]
I haven't been using Dokku for a few months and currently don't have any environment set up for testing something like this. If this still hasn't been created next time I set one up I can definitely give it a try, but yeah, not now.

**Comment by pynixwang** [comment]
@fgblomqvist yes PSQL  is more useful, but you must enter an interactive environment. and you can not run some command quietly.

**Comment by fgblomqvist** [comment]
@pynixwang Wrong. `psql -c "select * from my_table"`. The output can be redirect however you like it, or if you want to not see it at all you can just redirect it accordingly.

**Comment by pynixwang** [comment]
@fgblomqvist dokku postgresql has no `psql` command. maybe heroku has it.

**Comment by josegonzalez** [comment]
Thats actually false. We use it [here](https://github.com/dokku/dokku-postgres/blob/f30db928fb8a608327118ad2e0443594c8cd0bdf/functions#L21).

For the purposes of this issue, I am on-board with the feature. If someone wants to implement it, great. Otherwise, I'd appreciate keeping the chatter to a minimum, I get a ton of GH notifications and its hard to keep up sometimes :(

**Comment by cristianszwarc** [comment]
manual alternative
```
    dokku postgres:create some_amazing_db
    docker exec "dokku.postgres.some_amazing_db" su - postgres -c "dropdb some_amazing_db"
    docker exec "dokku.postgres.some_amazing_db" su - postgres -c "createdb -E utf8  some_amazing_db"
```

**Comment by josegonzalez** [comment]
Closing as there is an in-progress PR for this.
