### ISSUE TITLE
Where is the dump file?

### ISSUE THREAD

**Issue by flaviobarros** [dokku/dokku-postgres#144]
When I use

`dokku postgres:export mydb > mydb.dump`

where is the dump file located in the dokku server?

**Comment by joshmanders** [comment]
To expand on @josegonzalez's answer it's dumped wherever you run the command at. So if you run it in `/home/dokku` then its location is `/home/dokku/mydb.dump`

**Comment by josegonzalez** [comment]
Sorry, was responding from bed :P 

Hope the above helps, please comment if it doesn't.
