### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by sjensen85** [dokku/dokku-postgres#150]
Hello!

On my dokku server I recently ran out of disk space. After extending the partition, rebooting, and resizing the filesystem, I can't seem to get one of my postgres instances to fully start. When tailing logs I get: 

```
STATEMENT:  UPDATE public.clusteredjob SET  VERSION = $1 ,  NEXT_RUN = $2  WHERE JOB_ID=$3 AND VERSION=$4
ERROR:  could not extend file "base/16384/16492": No space left on device
HINT:  Check free disk space.
```

Other postgres databases can start, but also have a `No space left on device` error in logs.

```
LOG:  could not close temporary statistics file "pg_stat_tmp/global.tmp": No space left on device
```

I am using postgres 9.6.4 on Ubuntu. Everything is a standard dokku setup.

Have you seen this before? If so, do you know how to resolve? 

Please let me know any further info I can provide to make this easier.

Thanks!

**Comment by sjensen85** [comment]
It seems there are still some issues with my disk space as now dokku commands won't work at all. I will come back to this if I need.

Thanks!

**Comment by ohld** [comment]
Hi! I recently faced the similar issue. According to my DigitalOcean's machine `df -h` I have a plenty of free disk space. But Postgres keep telling me this issue.

![image](https://user-images.githubusercontent.com/5613295/114690713-a6a04380-9d1f-11eb-854a-56b03d750880.png)

**Comment by josegonzalez** [comment]
@ohld you're having a different issue. Mind filing a new ticket if you're still seeing this?

**Comment by bfontaine** [comment]
@ohld How did you fix your issue?
