### ISSUE TITLE
Way to change DNS of DB to be a subdomain of the Global Domain on Dokku?

### ISSUE THREAD

**Issue by chriscrosscutler** [dokku/dokku-postgres#151]
I'm trying to create a new db that is a subdomain of my sites domain instead of the generic db url. Is this possible? EX: `postgres://postgres:lasdfkje23asdk@dokku-postgres-dev:3000/dev` to `postgres://postgres:lasdfkje23asdk@dokku-postgres-dev.mywebsite.com:3000/dev`

**Comment by josegonzalez** [comment]
it is not currently possible, unfortunately, and there are no plans to do that. It uses the internal docker network name for dns.
