### ISSUE TITLE
docker: Error response from daemon: could not get container for dokku.postgres.oscar: No such container: dokku.postgres.oscar.

### ISSUE THREAD

**Issue by pythdasch** [dokku/dokku-postgres#156]
Hi,

I'm getting this error now without having done anything and it's quite alarming. How a container can disappear?

docker: Error response from daemon: could not get container for dokku.postgres.oscar: No such container: dokku.postgres.oscar.

Do someone know what happen?

**Comment by josegonzalez** [comment]
Did you restart and/or clear out your container? We don't do anything with services automatically, so I can only imagine it crashed - maybe oomkilled? - and then a deploy cleaned up the "unused" container.

You can start a new instance by running `dokku postgres:start SERVICE`.

**Comment by pythdasch** [comment]
this makes sense. I just started again and seems to work. I was first thinking someone hacked us and destroyed the databases. but this seems to work ! thanks Jose :)
