### ISSUE TITLE
Increase Pool Size

### ISSUE THREAD

**Issue by dastrika** [dokku/dokku-postgres#167]
I keep getting the following Error: 

> An ActiveRecord::ConnectionTimeoutError occurred in background at 2019-01-28 13:50:42 +0100 :
> 
> [safely] could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)
> /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:189:in `block in wait_poll'

In Rails i can set the default pool size in database.yml. how can i set this for dukku/dokku-postgres? 

I already increased the max database connections in postgressql.conf to 300 but i assume that Rails is pooling max 5 connections per worker. how can i change this setting?

**Comment by josegonzalez** [comment]
> i assume that Rails is pooling max 5 connections per worker

That sounds like a rails setting, not something we control?

**Comment by dastrika** [comment]
It's a setting typically in database.yml :

> production:
>   adapter: postgresql
>   encoding: unicode
>   database: sample_postgres_production
>   pool: 5
>   username: sample_postgres
>   password:

This file however is not published to dokku - the database settings are managed by linking a database, but i cannot set the pool setting anywhere

**Comment by dastrika** [comment]
Cool, thanks!
