### ISSUE TITLE
when a service is created, Does it automatically create the database as well. 

### ISSUE THREAD

**Issue by Utkarsh-vishnoi** [dokku/dokku-postgres#168]
I created a service and linked it with my application. The app logs are showing as the database doesn't exist. Is it the expected behaviour??

**Comment by josegonzalez** [comment]
How are you connecting to the database?

Also, multiple question marks or exclamation points don't convey more importance to questions :)

**Comment by Utkarsh-vishnoi** [comment]
Hi,
I have deployed a laravel app, and it cannot find the database. Using the official heroku buildpacks for php and nodejs. 

If I am manually logging into the service and creating the container, It works fine.

But shouldn't the db be created automatically when the service is created?(<---- Only One ???? mark)

**Comment by josegonzalez** [comment]
The database is created automatically. Is your laravel app reading the DATABASE_URL correctly?

**Comment by Utkarsh-vishnoi** [comment]
Yes, I double checked.

**Comment by josegonzalez** [comment]
Can you show how you are connecting to the database? Also, please show the output of the following:

```shell
dokku postgres:info YOUR_SERVICE
```

**Comment by Utkarsh-vishnoi** [comment]
Using the `getenv` to read the environment variable `DATABASE_URL` as shown below.

    $url = parse_url(getenv("DATABASE_URL"));
    $host = $url["host"];
    $username = $url["user"];
    $password = $url["pass"];
    $database = substr($url["path"], 1);
    
The output of `dokku postgres:info` is below

    =====> Container Information                                                                                                                                                                            
    Config dir:          /var/lib/dokku/services/postgres/atomix-database/config                                                                                                                     
    Data dir:            /var/lib/dokku/services/postgres/atomix-database/data                                                                                                                       
    Dsn:                 postgres://postgres:2d64129fb21bb8e9d167e90e448a95aa@dokku-postgres-atomix-database:5432/atomix_database                                                                    Exposed ports:       -                                                                                                                                                                           
    Id:                  bac4ae3c5a6eedbdc0bb7be165d762489e54cc2807beb341e1adb35a77904e03                                                                                                            
    Internal ip:         172.17.0.2                                                                                                                                                                  
    Links:               atomix                                                                                                                                                                       
    Service root:        /var/lib/dokku/services/postgres/atomix-database                                                                                                                            
    Status:              running                                                                                                                                                                     
    Version:             postgres:10.4

**Comment by josegonzalez** [comment]
What happens when you run `dokku postgres:connect atomix-database`?

**Comment by Utkarsh-vishnoi** [comment]
utkarsh@dokku:~$ dokku postgres:connect atomix-database
        psql: could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
        could not connect to server: Cannot assign requested address
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
        utkarsh@dokku:~$ dokku postgres:connect atomix-database
        psql: FATAL:  database "atomix_database" does not exist
        utkarsh@dokku:~$ dokku postgres:connect atomix-database
        psql: FATAL:  database "atomix_database" does not exist

First it shows error, I think it's because I just re-started the server. Next 2 times after 5-10 seconds, It cannot find the atomix-database.

**Comment by josegonzalez** [comment]
We definitely create the database [here](https://github.com/dokku/dokku-postgres/blob/master/functions#L78).

Can you try creating a new database and showing the logs of that create call? Maybe something failed, and the logs should show it.

**Comment by Utkarsh-vishnoi** [comment]
+ service_create_container test1-db                                                                                                                                                              
        + local SERVICE=test1-db                                                                                                                                                                         
        + local SERVICE_ROOT=/var/lib/dokku/services/postgres/test1-db                                                                                                                                   
        + local SERVICE_HOST_ROOT=/var/lib/dokku/services/postgres/test1-db                                                                                                                              
        ++ get_service_name test1-db                                                                                                                                                                     
        ++ declare 'desc=Retrieves a docker service label'                                                                                                                                               
        ++ declare SERVICE=test1-db                                                                                                                                                                      
        ++ echo dokku.postgres.test1-db                                                                                                                                                                  
        + local SERVICE_NAME=dokku.postgres.test1-db                                                                                                                                                     
        ++ cat /var/lib/dokku/services/postgres/test1-db/PASSWORD                                                                                                                                        
        + local PASSWORD=a72e479848f5297034a222a54e53b173                                                                                                                                                
        + local PREVIOUS_ID                                                                                                                                                                              
        ++ docker run --name dokku.postgres.test1-db -v /var/lib/dokku/services/postgres/test1-db/data:/var/lib/postgresql/data -e POSTGRES_PASSWORD=a72e479848f5297034a222a54e53b173 --env-file=/var/li b/dokku/services/postgres/test1-db/ENV -d --restart always --label dokku=service --label dokku.service=postgres postgres:10.4                                                                    + ID=d6bcb8d246188fc9df1e01a61602ae0230b639e3ce9b88c146cbdaaa3ec467a3                                                                                                                            
        + echo d6bcb8d246188fc9df1e01a61602ae0230b639e3ce9b88c146cbdaaa3ec467a3                                                                                                                          
        + dokku_log_verbose_quiet 'Waiting for container to be ready'                                                                                                                                    
        + declare 'desc=log verbose formatter (with quiet option)'                                                                                                                                       
        + [[ -z '' ]]                                                                                                                                                                                    
        + echo '       Waiting for container to be ready'                                                                                                                                                
        + docker run --rm --link dokku.postgres.test1-db:postgres dokkupaas/wait:0.2 -p 5432                                                                                                               
        ERROR: unable to connect

It finally shows up the error, It wasn't showing up early. I think there is something wrong with the `dokkupaaswait` container. Also without the `--trace`, It is not able to connect to the container

**Comment by josegonzalez** [comment]
Can you show the output of `docker log d6bcb8d246188fc9df1e01a61602ae0230b639e3ce9b88c146cbdaaa3ec467a3`?

**Comment by Utkarsh-vishnoi** [comment]
Here is the complete log for the container.

        utkarsh@dokku:~$ sudo docker logs d6bcb8d246188fc9df1e01a61602ae0230b639e3ce9b88c146cbdaaa3ec467a3
        The files belonging to this database system will be owned by user "postgres".
        This user must also own the server process.
        The database cluster will be initialized with locale "en_US.utf8".
        The default database encoding has accordingly been set to "UTF8".
        The default text search configuration will be set to "english".

        Data page checksums are disabled.

        fixing permissions on existing directory /var/lib/postgresql/data ... ok
        creating subdirectories ... ok
        selecting default max_connections ... 100
        selecting default shared_buffers ... 128MB
        selecting dynamic shared memory implementation ... posix
        creating configuration files ... ok
        running bootstrap script ... ok
        performing post-bootstrap initialization ... ok
        syncing data to disk ... ok

        Success. You can now start the database server using:

            pg_ctl -D /var/lib/postgresql/data -l logfile start


        WARNING: enabling "trust" authentication for local connections
        You can change this by editing pg_hba.conf or using the option -A, or
        --auth-local and --auth-host, the next time you run initdb.
        waiting for server to start....2019-02-16 10:23:47.044 UTC [38] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
        .2019-02-16 10:23:47.901 UTC [39] LOG:  database system was shut down at 2019-02-16 10:22:28 UTC
        2019-02-16 10:23:48.034 UTC [38] LOG:  database system is ready to accept connections
         done
        server started
        ALTER ROLE


        /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

        2019-02-16 10:23:48.479 UTC [38] LOG:  received fast shutdown request
        waiting for server to shut down....2019-02-16 10:23:48.576 UTC [38] LOG:  aborting any active transactions
        2019-02-16 10:23:48.579 UTC [38] LOG:  worker process: logical replication launcher (PID 45) exited with exit code 1
        2019-02-16 10:23:48.584 UTC [40] LOG:  shutting down
        .2019-02-16 10:23:49.624 UTC [38] LOG:  database system is shut down
         done
        server stopped

        PostgreSQL init process complete; ready for start up.

        2019-02-16 10:23:49.833 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
        2019-02-16 10:23:49.834 UTC [1] LOG:  listening on IPv6 address "::", port 5432
        2019-02-16 10:23:50.132 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
        2019-02-16 10:23:50.501 UTC [56] LOG:  database system was shut down at 2019-02-16 10:23:49 UTC
        2019-02-16 10:23:50.626 UTC [1] LOG:  database system is ready to accept connections
        2019-02-16 10:50:16.817 UTC [1] LOG:  received smart shutdown request
        2019-02-16 10:50:16.951 UTC [1] LOG:  worker process: logical replication launcher (PID 62) exited with exit code 1
        2019-02-16 10:50:16.959 UTC [57] LOG:  shutting down
        2019-02-16 10:50:18.340 UTC [1] LOG:  database system is shut down
        2019-02-17 12:22:03.038 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
        2019-02-17 12:22:03.038 UTC [1] LOG:  listening on IPv6 address "::", port 5432
        2019-02-17 12:22:03.799 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
        2019-02-17 12:22:05.873 UTC [21] LOG:  database system was shut down at 2019-02-16 10:50:17 UTC
        2019-02-17 12:22:08.280 UTC [1] LOG:  database system is ready to accept connections
        utkarsh@dokku:~$

**Comment by Utkarsh-vishnoi** [comment]
Any update on this??

**Comment by josegonzalez** [comment]
This should work now and our tests run docker as of 1.5.0 to verify that things work. Please re-open if this is still an issue with the exact setup you have and the steps used to recreate the issue.
