### ISSUE TITLE
Service alias determination seems broken

### ISSUE THREAD

**Issue by scflode** [dokku/dokku-postgres#169]
I am currently facing an issue where I try to link a second DB service to an app. As the DB was migrated there is already a `DATABASE_URL` alias set (`DOKKU_POSTGRES_YELLOW_URL`) and I receive the error "Unable to use default or generated URL alias".

Looking at the code in question (at least that is my guess):
```
service_alternative_alias() {
  declare desc="Retrieves an alternative alias for a service"
  declare EXISTING_CONFIG="$1"
  local COLORS=(AQUA BLACK BLUE FUCHSIA GRAY GREEN LIME MAROON NAVY OLIVE PURPLE RED SILVER TEAL WHITE YELLOW)
  local ALIAS;

  for COLOR in "${COLORS[@]}"; do
    ALIAS="${PLUGIN_ALT_ALIAS}_${COLOR}"
    local IN_USE=$(echo "$EXISTING_CONFIG" | grep "${ALIAS}_URL")
    if [[ -n $IN_USE ]]; then
      unset ALIAS
    fi
  done
  echo "$ALIAS"
}
```
this code (unless I am overlooking something) always iterates though all entries. So it will succeed only once (on the last element) or fail at that point if already taken.

I think the intention was more like this (but I am not 100% sure):

```
service_alternative_alias() {
  declare desc="Retrieves an alternative alias for a service"
  declare EXISTING_CONFIG="$1"
  local COLORS=(AQUA BLACK BLUE FUCHSIA GRAY GREEN LIME MAROON NAVY OLIVE PURPLE RED SILVER TEAL WHITE YELLOW)
  local ALIAS;

  for COLOR in "${COLORS[@]}"; do
    ALIAS="${PLUGIN_ALT_ALIAS}_${COLOR}"
    local IN_USE=$(echo "$EXISTING_CONFIG" | grep "${ALIAS}_URL")
    # We found a suitable candidate -> get out
    if [[ -z $IN_USE ]]; then
      break;
    fi
  done
  echo "$ALIAS"
}
```

The function is in [common-functions](https://github.com/dokku/dokku-postgres/blob/master/common-functions)

**Comment by scflode** [comment]
Just found out that using the `-a` flag is better for my use case.

**Comment by josegonzalez** [comment]
The automatic alias generation was fixed in https://github.com/dokku/dokku-postgres/commit/a5c60c2b076b3111595809e10c3098c7052be079#diff-984d248c3e37a7bb18530fd6eb22e8bf.
