### ISSUE TITLE
cannot create directory ‘/var/lib/dokku/services’: Permission denied when I try dokku postgres:create my database

### ISSUE THREAD

**Issue by voordev** [dokku/dokku-postgres#176]
```
dokku plugin:install https://github.com/dokku/dokku-postgres.git postgres
dokku postgres:create mydatabase
mkdir: cannot create directory ‘/var/lib/dokku/services’: Permission denied
Unable to create service directory
```

Do I manually need to add this folder? If so, what would be the permissions for it?
Or is this an installation error. Im running latest dokku 0.14 release.

Kind regards

**Comment by voordev** [comment]
Ok tried adding folder manual 
Permissions chmod 600 it still fails with same error.

Did I miss something?

**Comment by josegonzalez** [comment]
What is the output of the following command:

```
ls -lah /var/lib/dokku
```

**Comment by alertcode** [comment]
I have the same problem , but I have resolve the issue like this.

mkdir services /var/lib/dokku/services
chown -R dokku /var/lib/dokku/services
chgrp -R dokku /var/lib/dokku/services

and execute "dokku postgres:create databasename " again

**Comment by josegonzalez** [comment]
If someone sees this problem, before running the lines that @alertcode wrote, please run the command:

```
ls -lah /var/lib/dokku
```

And paste the output here. Thank you.

**Comment by josegonzalez** [comment]
Closing as there hasn't been an update in a while.

**Comment by ochorocho** [comment]
@josegonzalez had the same issue on my installation

This is the output before creating the folder and changing the permissions:

```
# ls -lah /var/lib/dokku
total 36K
drwxr-xr-x  6 root  root  4.0K Jul 31 12:53 .
drwxr-xr-x 34 root  root  4.0K Jul 31 12:52 ..
drwxr-xr-x  7 root  root  4.0K Jul 31 12:54 config
drwxr-xr-x  4 dokku dokku 4.0K Jul 31 12:53 core-plugins
drwxr-xr-x  6 dokku dokku 4.0K Jul 31 12:54 data
-rw-r--r--  1 root  root    41 Jun 18 18:37 GIT_REV
drwxr-xr-x  4 dokku dokku 4.0K Jul 31 12:53 plugins
-rw-r--r--  1 root  root     7 Jun 18 18:37 STABLE_VERSION
-rw-r--r--  1 root  root     7 Jun 18 18:37 VERSION
```

**Comment by Anonymous6214** [comment]
same question while creating app using dokku adds:create ledokku

```
 !     Unable to create network config directory for ledokku: mkdir /var/lib/dokku/config/network: permission denied
 !     Unable to create ps config directory for ledokku: mkdir /var/lib/dokku/config/ps: permission denied
 ```
And here is the output while typing ls -lah /var/lib/dokku:
```
drwxr-xr-x  6 root  root  4.0K  1/ 12 18:41 .
drwxr-xr-x 44 root  root  4.0K  1/ 12 18:35 ..
drwxr-xr-x  2 root  root  4.0K  1/ 12 18:41 config
drwxr-xr-x  4 dokku dokku 4.0K  1/ 12 17:54 core-plugins
drwxr-xr-x  3 dokku dokku 4.0K  1/ 12 18:48 data
drwxr-xr-x  4 dokku dokku 4.0K  1/ 12 17:54 plugins
-rw-r--r--  1 root  root     7  1/ 12 17:53 VERSION

```
os: manjaro

**Comment by Anonymous6214** [comment]
I get it, thanks for replying
