### ISSUE TITLE
Import .sql file

### ISSUE THREAD

**Issue by mewben** [dokku/dokku-postgres#18]
Is there a way to import .sql files?

Right now, it throws this error:
```
pg_restore: [archiver] input file does not appear to be a valid archive
```

**Comment by Flink** [comment]
Yes `pg_restore` only works with non-plain-text formats. So this should work instead: `dokku postgres:connect app < file.sql`

**Comment by josegonzalez** [comment]
@Flink what do you mean by "non-plain-text formats"? In both the user's question and your example, you are both importing a .sql file.

**Comment by Flink** [comment]
I mean what’s the man means :)
> pg_restore is a utility for restoring a PostgreSQL database from an archive created by pg_dump(1) in one of the non-plain-text formats.

So you can use `postgres:import` for any non-plain-text formats created by `pg_dump`. For `.sql` files you’ll need to feed directly `psql` thus using `postgres:connect` instead.

**Comment by josegonzalez** [comment]
Gotcha, makes sense. Mind documenting that in the readme?

**Comment by Flink** [comment]
Not at all!

**Comment by mewben** [comment]
Thank you @Flink but I got this error running the command:
```
FATA[0000] cannot enable tty mode on non tty input
```

**Comment by josegonzalez** [comment]
Are you trying to import across an ssh connection?

**Comment by mewben** [comment]
No, I logged in to the server and run dokku postgres:connect ...

**Comment by mewben** [comment]
I tried manually executing this line without the `-t` and it worked perfectly:
https://github.com/dokku/dokku-postgres/blob/master/commands#L171

**Comment by josegonzalez** [comment]
@Flink might make sense to use the `common/functions` function `has_tty` [like so](https://github.com/progrium/dokku/blob/master/plugins/00_dokku-standard/commands#L163-L164).

**Comment by Flink** [comment]
@josegonzalez yep, on it.
