### ISSUE TITLE
Unable to restore backup locally

### ISSUE THREAD

**Issue by andyklimczak** [dokku/dokku-postgres#183]
Hi, I am trying to load my s3 backup of the pg database for my test project in my local postgres. 

First I'm running `dokku postgres:backup myapp bucket`, then manually download the `.tgz` file from s3. Then I try to restore on my local using a similar command to [`postgres:restore`](https://github.com/dokku/dokku-postgres/blob/b414ca165aebafa21f3ee1a743b15c70321b5bc7/functions#L121):
```
pg_restore -h localhost -cO -d myapp_development -v "/tmp/backup.tgz"
```

but I get back:
```
pg_restore: [archiver] input file does not appear to be a valid archive
```
I feel like I'm missing something small. I've been digging through older issues, but haven't been able to find an answer.

dokku postgres plugin version: 1.8.0
dokku postgres database version: 11.2
local postgres version: 11.3

Thanks!

**Comment by josegonzalez** [comment]
You probably want to extract the tar.gz file.

**Comment by andyklimczak** [comment]
I thought I tried that (extracting creates a `backup` directory with a file called `export` inside), but will triple check

**Comment by andyklimczak** [comment]
Oops, that was totally it, was able to restore with `pg_restore -h localhost -d app_development export` after extracting the backup.tgz

My bad, thanks a ton!

**Comment by stefsava** [comment]
If the database backup is large and you do not want expand it before the restore,
you can use unix pipe

```bash
tar xfzO postgres-appdb-2020-03-11-01-00-11.tgz | pg_restore -d app_development -c
```
