### ISSUE TITLE
[Feature request] Add --shm-size option to postgres:create

### ISSUE THREAD

**Issue by turicas** [dokku/dokku-postgres#201]
The default `/dev/shm` size is `64MB` and PostgreSQL can easily need more space if you're running queries with large results. The best way to solve this problem is to create the PostgreSQL container passing `--shm-size=<greater-size>` (as stated in "Caveats" section on [docker postgres docs](https://hub.docker.com/_/postgres)). The other option is not so simple: change container's `ShmSize` property - this [is not supported by docker](https://github.com/docker/cli/issues/1278) and requires some hacking and restarting docker daemon (which is not desirable).

**Comment by turicas** [comment]
If you're using Dokku and got an error like this:

```
ERROR:  could not resize shared memory segment "/PostgreSQL.2088012784" to 50438144 bytes: No space left on device
```
The only solution I've found **needs docker service restarting**:

```shell
PG_NAME="<your-docker-postgres-service-name>"
PG_CONTAINER_ID=$(docker inspect -f '{{ .ID }}' dokku.postgres.$PG_NAME)
PG_HOST_CONFIG=/var/lib/docker/containers/$PG_CONTAINER_ID/hostconfig.json
service docker stop
sed -i 's/"ShmSize":[0-9]\+,/"ShmSize":268435456,/' $PG_HOST_CONFIG
service docker start
```

> Note: in the example above the `/dev/shm` is set to `256MB` (268435456 bytes).

**Comment by Friss** [comment]
I also ran into this today. I ended up needing just over 1 gig for my DB. 

You may also need to restart any deployed apps with `dokku ps:restart app-name`. 

I needed to do that for nginx to work.

**Comment by DavraYoung** [comment]
Same problem

> ERROR:  could not resize shared memory segment "/PostgreSQL.1657416213" to 8388608 bytes: No space left on device

**Comment by turicas** [comment]
Thanks, @josegonzalez! =)

**Comment by Timmitry** [comment]
☝️ As can be seen in the linked pull request, there is now an option available to set this when [creating the database](https://github.com/dokku/dokku-postgres#create-a-postgres-service):

> -s|--shm-size SHM_SIZE: override shared memory size for postgres docker container

This should probably be the preferred solution, at least for new containers 😉

**Comment by rrr2rrr** [comment]
Hello! Is it possible to change this parameter for existing containers?
```
root@Ubuntu-2204-jammy-amd64-base ~ # dokku postgres:upgrade lake --shm-size 4g
-----> Service lake already running postgres:16.3
```
So I can't change the shm

**Comment by jimmypoulsen** [comment]
Hey guys. Just stumbled into this issue. I have an existing Dokku Postgres container running and I can't seem to get @turicas solution to work on that. Doesn't Dokku Postgres have some built in functionality for this?

**Comment by josegonzalez** [comment]
If you create a file (owned by the `dokku` user) named `SHM_SIZE` in the service root folder and then stop/start the postgres container, that should cause the plugin to pick up the value.

Atm this isn't exposed except on service create/upgrade/clone.

**Comment by jimmypoulsen** [comment]
> If you create a file (owned by the `dokku` user) named `SHM_SIZE` in the service root folder and then stop/start the postgres container, that should cause the plugin to pick up the value.
> 
> Atm this isn't exposed except on service create/upgrade/clone.

You just saved my life 😆 Thank you! 🙏

**Comment by josegonzalez** [comment]
@jimmypoulsen remember to donate to the project ;)

**Comment by jimmypoulsen** [comment]
@josegonzalez already done! 💯 🥇
