### ISSUE TITLE
Question - How to upgrade to the latest version of PG

### ISSUE THREAD

**Issue by sushilbansal** [dokku/dokku-postgres#210]
## Description of problem
How to upgrade to the latest version of PG

I am switching over from Heroku. Heroku runs the latest release of PG. I am having some troubles restoring the DB on to Dokku PG instance as it is one major version behind the latest release.

### How reproducible
N/A

### Steps to Reproduce
N/A

**Comment by Schlepptop** [comment]
Do you have an existing postgres service running on dokku that runs on an older version and that you want to upgrade or do you just want to create a new service with a more recent version?

**Comment by sushilbansal** [comment]
i can do either. I just started a new instance with no data. I do not mind upgrding it or starting a new one.

**Comment by Schlepptop** [comment]
You can set the POSTGRES_IMAGE and POSTGRES_IMAGE_VERSION env vars before creating the service to deviate from the defaults (postgres:11.6)

**Comment by sushilbansal** [comment]
Legend @Schlepptop . Thanks a lot for the help. Anyone looking for the exact steps:
1) install the postgres latest version
-- docker pull postgres:latest

2) Set the environment variables:
-- export POSTGRES_IMAGE="postgres"
-- export POSTGRES_IMAGE_VERSION="latest"

3) dokku postgres:create service_name

4) dokku postgres:link service_name app_name
