### ISSUE TITLE
postgres:connect process leak

### ISSUE THREAD

**Issue by shulcsm** [dokku/dokku-postgres#212]
## Description of problem
There seems to be an issue with postgres:connect leaking psql process and subsequently connections.

https://github.com/dokku/dokku-postgres/blob/master/functions#L20
If psql does not return but you terminate / kill ssh connection you are left with unattached psql process.
I'm not familiar with semantics, but shouldn't there be some kind of signal trapping for foreground processes? I suspect this affects other plugins.

**Comment by shulcsm** [comment]
For the worse killing postgres connections does not solve the issue - processes are still there. I suspect psql does not exit in case of terminated connection because it's run in interactive mode.

**Comment by josegonzalez** [comment]
Interesting. That maybe sounds like a bug in psql? Thoughts on how we might fix it?

**Comment by shulcsm** [comment]
I don't think it has anything to do with psql in particular.

1. If you do something like: `shell ssh user@hostdocker exec -it container sleep 60`  
2. Kill the ssh
3. sleep will still be running (including the docker runc / docker-shim). I think it just gets detached.

I'm not sure if TERM is sent or STDIN just gets broken but i think that should be trapped and propagated to exec.
That should probably be done for any interactive dokku / sshcommand call?

I hope this helps. Sorry, i'm way out of my depth here.

**Comment by shulcsm** [comment]
This seems related https://github.com/moby/moby/issues/9098
Seems like the there is not easy / pretty fix.
