### ISSUE TITLE
Restore PostGIS installation instructions in README?

### ISSUE THREAD

**Issue by brylie** [dokku/dokku-postgres#213]
There used to be instructions for installing PostGIS in the readme. However, those instructions appear to have been removed. What was the reasoning for the removal? May we please add the PostGIS installation instructions back in the README?

## PostGIS installation instructions

Official Postgres docker images doesn't include postgis extension. 

To be able to use postgis, you will need postgres+postgis docker container compatible with official ones. 

You can use for example `postgis/postgis` container:

```
dokku postgres:create postgis-database --image "postgis/postgis" --image-version "latest"
dokku postgres:connect postgis-database

CREATE EXTENSION postgis;
```

Reference issue: https://github.com/dokku/dokku-postgres/issues/52

**Comment by Schlepptop** [comment]
I'd say the more general instructions on how to specify an image/version to create the DB with already cover this specific case, don't they?

**Comment by brylie** [comment]
Since PostGIS is a fairly common extension and has already been discussed in the Dokku issue tracker, it might be nice to include a small section in the README with specific steps to use the PostGIS image and run the `CREATE EXTENSION postgis` command.

**Comment by iandees** [comment]
+1 on this, if only for the Google SEO for when I forgot how to do it 😄

**Comment by brylie** [comment]
@iandees can you please verify whether the following commands are the correct/idiomatic way to configure PostGIS via Dokku?

```
dokku postgres:create postgis-database --image "postgis/postgis" --image-version "latest"
dokku postgres:connect postgis-database

CREATE EXTENSION postgis;
```

**Comment by Schlepptop** [comment]
For me, `postgis/postgis` already comes with the postgis extension enabled, and running `CREATE EXTENSION postgis;` errors with `extension "postgis" already exists`.
Either way, it would be working afterwards, so I guess your snippet is okay.
Alternatively, one could suggest 
``` dokku postgres:enter postgis-database psql -h localhost -U postgres -c "CREATE EXTENSION postgis;" "postgres"```
so people who don't want to bother with the psql shell can get this working as well?

**Comment by synthomat** [comment]
@Schlepptop you can use `CREATE EXTENSION IF NOT EXISTS postgis;` instead!

**Comment by ppawlak** [comment]
No postgis specific, but does using a custom docker image is the recommended way to have a custom extension installed in my database? 
For instance I'd like to have the timescaledb extension available. Should I create a postgres based docker image which add installation of this extension?

**Comment by josegonzalez** [comment]
Using a custom postgres image works great, and if you want to customize what gets included with a datastore on creation, thats the recommended way.
