### ISSUE TITLE
How to upgrade to Postgres 13.2

### ISSUE THREAD

**Issue by fandy** [dokku/dokku-postgres#219]
Are there any docs for upgrading Postgres to v13? I created it but noticed that it defaults to v11.6.

Running `dokku Postgres:upgrade app -I 13.2` results in `Unable to proceed with upgrade, image postgres:12.6 does not exist` error, even though the image is valid on Dockerhub.

**Comment by josematiasarevalo** [comment]
☝️ same question here

**Comment by josematiasarevalo** [comment]
@fandy Actually, this approach solved my issue: https://github.com/dokku/dokku-postgres/issues/178#issuecomment-764829300

**Comment by fabriciobonjorno** [comment]
point_up same question here

**Comment by f3l1x** [comment]
I have successfully upgraded 11.6 to 13.2 using (https://github.com/dokku/dokku-postgres/issues/178#issuecomment-764829300).

```
docker pull postgres:13.2
dokku ps:stop $app
dokku postgres:export $db > /tmp/live-export
dokku postgres:unlink $db $app
dokku postgres:destroy $db
dokku postgres:create $db --image-version 13.2
dokku postgres:import $db < /tmp/live-export
dokku postgres:link $db $app
dokku ps:start live
```

**Comment by aaronstillwell** [comment]
To clarify for future readers, the issue here appeared to be the image not existing on the host. Hence a `docker pull postgres:13.2` is required.

**Comment by schmijos** [comment]
Would someone mind to add this to the README or adjust the command output to reflect that you may have to pull the image first? I think even automatically pulling would be better than the current situation.

**Comment by josegonzalez** [comment]
The command should now error with a message saying the image doesn't exist.

**Comment by josegonzalez** [comment]
And now this process is documented!
