### ISSUE TITLE
Exposing detailed variables

### ISSUE THREAD

**Issue by andersem** [dokku/dokku-postgres#22]
Using this for a dropwizard-application requires to split up the variables into one for username, one for password and one for url. I forked another postgres-plugin to support this: https://github.com/andersem/dokku-pg-plugin, but I thought it would be better to use the official one.

This is how I split the variables in my fork. Is this doable in this plugin?

```
DATABASE_URL=postgres://root:RDSBYlUrOYMtndKb@172.17.42.1:49187/db
DATABASE_HOST=172.17.42.1
DATABASE_PORT=49187
DATABASE_USER=root
DATABASE_PASSWORD=RDSBYlUrOYMtndKb
```

**Comment by josegonzalez** [comment]
Can you not make the dropwizard app use the single `DATABASE_URL` env var for connecting to the instance?

**Comment by andersem** [comment]
It can probably be done, but by what I can see it would be a hack (DW doesn't seem too flexible here), and I thought maybe it would be more correct to do it in the plugin.

Would it be wrong to expose them here, my thought was that offering more flexibility for using the plugin would be good?

**Comment by josegonzalez** [comment]
I'm personally against this - we're actually trying to get our developers at work to standardize on `_URL` to reduce the env vars we set for applications - but I defer to @Flink here. Thoughts?

**Comment by andersem** [comment]
I understand it might be a philosophical question, and you don't want a
variable for every possible use case. I'll leave the decision to you guys.

tir. 22. sep. 2015, 06.09 skrev Jose Diaz-Gonzalez <notifications@github.com

**Comment by Flink** [comment]
Yes I agree with @josegonzalez, those variables aren’t standards I think. If another app needs, say, `DB_HOST` or `DB_PASS` or `DATABASE_PASS`, what do we do? We add them also?
The `DATABASE_URL` scheme is something widespread for some years now, thanks to Heroku mainly I think. By the way, Heroku won’t give you anything else than the `DATABASE_URL` var.

Technically, all the needed information is present in this variable and modern applications should be able to use that.

Another thing you can do, is to declare those variables with `dokku config:set` like you’d do on Heroku. One thing that can be annoying is if the IP of the container changes but we can (and should I think) do something for that (by using an alias used in `--link` option). We should also think about exporting the `DATABASE_URL` with `dokku config:set` so it will be available like any other env var (and like on Heroku on more time ;)).

**Comment by andersem** [comment]
Ok, I understand. I'll try `config:set`, then :)

**Comment by josegonzalez** [comment]
We set the `DATABASE_URL` via a docker-arg so it disappears when the container is not linked. Much easier than dealing with "omg you unset my config" problems.

**Comment by Flink** [comment]
yeah but also it is not exposed in the app config, so it’s not easily available. We should have a behavior similar to Heroku on this one. I’m working on it, we’ll see :)
