### ISSUE TITLE
How to install extension to existing Postgres?

### ISSUE THREAD

**Issue by ohld** [dokku/dokku-postgres#222]
Hi!

I need to install [Pgrouting](https://docs.pgrouting.org/3.1/en/pgRouting-installation.html) extension to my `dokku-postgres` database which is already populated with a huge amount of data from my Django app. Moreover, this extension requires `postGIS` to be installed too. 

I searched all issues and couldn't find the way how to install it. Maybe someone can help? 

I'm on the latest `Dokku` and latest `dokku-postgres` now.

**Comment by josegonzalez** [comment]
Make a custom Dockerfile that installs the extension, build the image, and use it for your database? You'll need to stop/start, but it should work?

I would export the database contents and try it on a new service to verify of course.

**Comment by ohld** [comment]
Thanks for the reply! I'll try it out and then reopen if I'll have any troubles.

**Comment by HummingBird24** [comment]
@ohld Care to share a skeleton of what you added to your Dockerfile to do this?
