### ISSUE TITLE
Question: Is there a way to specify a locale when creating a database

### ISSUE THREAD

**Issue by holgi** [dokku/dokku-postgres#230]
## Description of problem

I created an app for Synapse (matrix home server) and linked it to the postgres service. When starting up Synapse, it complains that the locale needs to be set to "C".

I did not find any solution in the documentation about setting the locale for a postgress database  and wanted to know if it is currently supported and I just couldn't figure it out or if it would be possible to add this.

(my hacky solution was to temporarily edit the functions file)

Thanks for your work!

**Comment by josegonzalez** [comment]
You can modify the database to be whatever locale you want after the service has been created. We only specify the locale on container creation.

**Comment by DanielRub** [comment]
You can pass a custom-env as a param when creating the postgres service like this
`	 dokku postgres:create synapsedb --custom-env "LC_ALL=C"
`

**Comment by holgi** [comment]
Thank you, I missed this option :-)
