### ISSUE TITLE
Question: How to take dump of single table and restore to another dokku instance?

### ISSUE THREAD

**Issue by amitsavani** [dokku/dokku-postgres#232]
I have a large table to export from a dokku instance on one server and import to another dokku instance on another server.

Tacking the whole DB dump is straightforward but needs to export/mport a single table only.

**Comment by josegonzalez** [comment]
You can do that the same way you would on any other system. 

Example from stackoverflow: https://stackoverflow.com/a/3682944

I won't be supporting a partial import/export in this plugin, but the above should fit your needs.
