### ISSUE TITLE
how to import csv into dokku/postgresql e.g. with \copy

### ISSUE THREAD

**Issue by sstolzenberg** [dokku/dokku-postgres#233]
Hello everyone,
I tried:

rsync -av test.csv root@$MYIP:
ssh root@$MYIP
ls test.csv
dokku postgres:connect mydb
\COPY test FROM '/root/test.csv' DELIMITER ',' CSV HEADER;
/root/test.csv: No such file or directory

- can somebody entangle my confusion?

Thank you very much!
- Sebastian

**Comment by aaronstillwell** [comment]
The postgres container will by default not simply have access to the entire host disk. The easiest way to do this might be to copy the csv file into the directory that is mounted as a volume to your postgres container, which you'll be able to access from within the container itself.

Try `dokku postgres:info <pg-service-name>` and look at the "data dir" output to see where on the host the mounted directory exists. Move your csv file here, then within the postgres container you should be able to access it at `/var/lib/postgresql/data`.

Note I haven't tried this myself.

**Comment by sstolzenberg** [comment]
Great, thanks a lot for your help,
this works exactly as you suggested!
- Sebastian
