### ISSUE TITLE
Documentation (or feature) missing - restoring from backup

### ISSUE THREAD

**Issue by m-z-b** [dokku/dokku-postgres#243]
The README.md file is excellent on options for creating and scheduling backups. 

However, there is no description of how to _restore_ from a backup.

It wasn't obvious for me. Unless I've missed an easier way, it involves extracting the `export` file from the `backup` directory in the compressed tar file, then piping this into `postgres:import`.  

A command:
```
postgres:restore <service> < my_backup_file
```
would simplify this. But improved documentation would be an immediate fix.

**Comment by josegonzalez** [comment]
You do need to extract the file, which is documented here: https://github.com/dokku/dokku-postgres#create-a-backup-of-the-postgres-service-to-an-existing-s3-bucket

**Comment by josegonzalez** [comment]
You'll see a section that goes on about `postgres:import`.

**Comment by m-z-b** [comment]
Don't know how I missed that! Perhaps I had case sensitivity on when searching the page for the word "restore".  

Can I suggest adding a heading for the search impaired like me?  It's something that may need to be found in a hurry.

Incidentally the backup file example would be more accurate if it read `backup/export` not `backup-folder/export`
