### ISSUE TITLE
`postgres:upgrade`: Permission denied

### ISSUE THREAD

**Issue by jfilter** [dokku/dokku-postgres#245]
## Description of problem

Can't use `postgres:upgrade` with the latest dokku and dokku-postgres version.

### Steps to Reproduce

1. docker pull postgres:11
2. docker tag postgres:11 foo
3. dokku postgres:upgrade app-db -I foo

#### Actual Results

```
/var/lib/dokku/plugins/enabled/postgres/common-functions: line 277: /var/lib/dokku/services/postgres/app-db/IMAGE: Permission denied
```

#### Expected Results

Upgrade should work.

### `dokku report APP_NAME` output

-----> uname: Linux prod1 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
-----> memory:
                     total        used        free      shared  buff/cache   available
       Mem:           3839         992        1575          45        1271        2533
       Swap:             0           0           0
-----> docker version:
       Client: Docker Engine - Community
        Version:           20.10.12
        API version:       1.41
        Go version:        go1.16.12
        Git commit:        e91ed57
        Built:             Mon Dec 13 11:45:33 2021
        OS/Arch:           linux/amd64
        Context:           default
        Experimental:      true

       Server: Docker Engine - Community
        Engine:
         Version:          20.10.12
         API version:      1.41 (minimum version 1.12)
         Go version:       go1.16.12
         Git commit:       459d0df
         Built:            Mon Dec 13 11:43:42 2021
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.4.12
         GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
        runc:
         Version:          1.0.2
         GitCommit:        v1.0.2-0-g52b36a2
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info:
       Client:
        Context:    default
        Debug Mode: true
        Plugins:
         app: Docker App (Docker Inc., v0.9.1-beta3)
         buildx: Docker Buildx (Docker Inc., v0.7.1-docker)

       Server:
        Containers: 7
         Running: 7
         Paused: 0
         Stopped: 0
        Images: 69
        Server Version: 20.10.12
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Cgroup Version: 1
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
WARNING: No swap limit support
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
        runc version: v1.0.2-0-g52b36a2
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: default
        Kernel Version: 5.4.0-91-generic
        Operating System: Ubuntu 20.04.3 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 3
        Total Memory: 3.75GiB
        Name: prod1
        ID: 2OQG:J4DU:O3NH:3VM4:4B2A:4OI6:VM5X:UT5P:Q4NL:TS3O:3VYY:UJ62
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false

-----> git version: git version 2.25.1
-----> sigil version: 0.7.1build+1ec3006
-----> herokuish version:
       herokuish: 0.5.33
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v232
         heroku-buildpack-nodejs    v189
         heroku-buildpack-clojure   v87
         heroku-buildpack-python    v204
         heroku-buildpack-java      v69
         heroku-buildpack-gradle    v35
         heroku-buildpack-scala     v91
         heroku-buildpack-play      v26
         heroku-buildpack-php       v201
         heroku-buildpack-go        v157
         heroku-buildpack-nginx     v15
         buildpack-null             v3
-----> dokku version: dokku version 0.26.6
-----> plugn version: plugn: 0.7.1build+9bf216b
-----> dokku plugins:
         00_dokku-standard    0.26.6 enabled    dokku core standard plugin
         20_events            0.26.6 enabled    dokku core events logging plugin
         app-json             0.26.6 enabled    dokku core app-json plugin
         apps                 0.26.6 enabled    dokku core apps plugin
         builder              0.26.6 enabled    dokku core builder plugin
         builder-dockerfile   0.26.6 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.26.6 enabled    dokku core builder-herokuish plugin
         builder-null         0.26.6 enabled    dokku core builder-null plugin
         builder-pack         0.26.6 enabled    dokku core builder-pack plugin
         buildpacks           0.26.6 enabled    dokku core buildpacks plugin
         certs                0.26.6 enabled    dokku core certificate management plugin
         checks               0.26.6 enabled    dokku core checks plugin
         common               0.26.6 enabled    dokku core common plugin
         config               0.26.6 enabled    dokku core config plugin
         cron                 0.26.6 enabled    dokku core cron plugin
         docker-options       0.26.6 enabled    dokku core docker-options plugin
         domains              0.26.6 enabled    dokku core domains plugin
         enter                0.26.6 enabled    dokku core enter plugin
         git                  0.26.6 enabled    dokku core git plugin
         letsencrypt          0.12.1 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.26.6 enabled    dokku core logs plugin
         maintenance          0.5.1 enabled    Maintenance mode for apps
         network              0.26.6 enabled    dokku core network plugin
         nginx-vhosts         0.26.6 enabled    dokku core nginx-vhosts plugin
         plugin               0.26.6 enabled    dokku core plugin plugin
         postgres             1.17.0 enabled    dokku postgres service plugin
         proxy                0.26.6 enabled    dokku core proxy plugin
         ps                   0.26.6 enabled    dokku core ps plugin
         redirect             0.7.1 enabled    Plugin for managing application redirects
         redis                1.18.0 enabled    dokku redis service plugin
         registry             0.26.6 enabled    dokku core registry plugin
         repo                 0.26.6 enabled    dokku core repo plugin
         resource             0.26.6 enabled    dokku core resource plugin
         run                  0.26.6 enabled    dokku core run plugin
         scheduler            0.25.6 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.26.6 enabled    dokku core scheduler-docker-local plugin
         scheduler-null       0.26.6 enabled    dokku core scheduler-null plugin
         shell                0.26.6 enabled    dokku core shell plugin
         ssh-keys             0.26.6 enabled    dokku core ssh-keys plugin
         storage              0.26.6 enabled    dokku core storage plugin
         trace                0.26.6 enabled    dokku core trace plugin
=====> xx app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:
=====> xx app information
       App created at:                1639482910
       App deploy source:
       App deploy source metadata:
       App dir:                       /home/dokku/xx
       App locked:                    false
=====> xx builder information
       Builder build dir:
       Builder computed build dir:
       Builder computed selected:
       Builder global build dir:
       Builder global selected:
       Builder selected:
=====> xx builder-dockerfile information
       Builder dockerfile computed dockerfile path: Dockerfile
       Builder dockerfile global dockerfile path: Dockerfile
       Builder dockerfile dockerfile path:
=====> xx builder-pack information
       Builder pack computed projecttoml path: project.toml
       Builder pack global projecttoml path: project.toml
       Builder pack projecttoml path:
=====> xx buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-20
       Buildpacks global stack:
       Buildpacks list:
       Buildpacks stack:
=====> xx ssl information
       Ssl dir:                       /home/dokku/xx/tls
       Ssl enabled:                   true
       Ssl hostnames:                 xx.de www.xx.de
       Ssl expires at:                Feb 20 22:00:17 2022 GMT
       Ssl issuer:                    C = US, O = Let's Encrypt, CN = R3
       Ssl starts at:                 Nov 22 22:00:18 2021 GMT
       Ssl subject:                   subject=CN = xx.de
       Ssl verified:                  self signed
=====> xx checks information
       Checks disabled list:          none
       Checks skipped list:           none
=====> xx cron information
       Cron task count:               0
=====> xx docker options information
       Docker options build:          --link dokku.postgres.xx-db:dokku-postgres-xx-db --link dokku.redis.xx-redis:dokku-redis-xx-redis
       Docker options deploy:         --link dokku.postgres.xx-db:dokku-postgres-xx-db --link dokku.redis.xx-redis:dokku-redis-xx-redis --restart=on-failure:10 -v /var/lib/dokku/data/storage/xx-media:/media
       Docker options run:            --link dokku.postgres.xx-db:dokku-postgres-xx-db --link dokku.redis.xx-redis:dokku-redis-xx-redis -v /var/lib/dokku/data/storage/xx-media:/media
=====> xx domains information
       Domains app enabled:           true
       Domains app vhosts:            xx.de www.xx.de
       Domains global enabled:        false
       Domains global vhosts:
=====> xx git information
       Git deploy branch:             main
       Git global deploy branch:      master
       Git keep git dir:              false
       Git rev env var:               GIT_REV
       Git sha:                       xx
       Git last updated at:           1638550528
=====> xx logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:
       Logs max size:
       Logs vector sink:
=====> xx network information
       Network attach post create:
       Network attach post deploy:
       Network bind all interfaces:          false
       Network computed attach post create:
       Network computed attach post deploy:
       Network computed bind all interfaces: false
       Network computed initial network:
       Network computed tld:
       Network global attach post create:
       Network global attach post deploy:
       Network global bind all interfaces:   false
       Network global initial network:
       Network global tld:
       Network initial network:
       Network static web listener:
       Network tld:
       Network web listeners:                172.17.0.6:5000
=====> xx nginx information
       Nginx access log format:
       Nginx access log path:         /var/log/nginx/xx-access.log
       Nginx bind address ipv4:
       Nginx bind address ipv6:       ::
       Nginx client max body size:
       Nginx disable custom config:   false
       Nginx error log path:          /var/log/nginx/xx-error.log
       Nginx global hsts:             true
       Nginx computed hsts:           true
       Nginx hsts:                    true
       Nginx hsts include subdomains: true
       Nginx hsts max age:            15724800
       Nginx hsts preload:            false
       Nginx proxy buffer size:       4096
       Nginx proxy buffering:         on
       Nginx proxy buffers:           8 4096
       Nginx proxy busy buffers size: 8192
       Nginx proxy read timeout:      60s
       Nginx last visited at:         1639483735
       Nginx x forwarded for value:   $remote_addr
       Nginx x forwarded port value:  $server_port
       Nginx x forwarded proto value: $scheme
       Nginx x forwarded ssl:
=====> xx proxy information
       Proxy enabled:                 true
       Proxy port map:                http:80:5000 https:443:5000
       Proxy type:                    nginx
=====> xx ps information
       Deployed:                      true
       Processes:                     3
       Ps can scale:                  false
       Ps computed procfile path:     Procfile
       Ps global procfile path:       Procfile
       Ps procfile path:
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       true
       Status beat 1:                 running (CID: 9e10fc8886d)
       Status web 1:                  running (CID: 3445a0ffd09)
       Status worker 1:               running (CID: f5e4b72356b)
=====> xx registry information
       Registry computed image repo:      dokku/xx
       Registry computed push on release: false
       Registry computed server:
       Registry global push on release:
       Registry global server:
       Registry image repo:
       Registry push on release:
       Registry server:
       Registry tag version:
=====> xx resource information
=====> xx scheduler information
       Scheduler computed selected:   docker-local
       Scheduler global selected:     docker-local
       Scheduler selected:
=====> xx scheduler-docker-local information
       Scheduler docker local disable chown:
       Scheduler docker local parallel schedule count:
=====> xx storage information
       Storage build mounts:
       Storage deploy mounts:         -v /var/lib/dokku/data/storage/xx:/media
       Storage run mounts:            -v /var/lib/dokku/data/storage/xx:/media

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:

deb on VPS (Hetzner Cloud)

**Comment by andresribeiro** [comment]
Same here

**Comment by josegonzalez** [comment]
What are the permissions on those files? Specifically, can you run the following?

```
ls -lah /var/lib/dokku/services/*/*
```

**Comment by josegonzalez** [comment]
This was fixed in the latest patch release for all datastore plugins (so 1.19.2 for dokku-postgres). The issue was we were writing those files as the root user, but not resetting perms to the dokku system user.
