### ISSUE TITLE
The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

### ISSUE THREAD

**Issue by kamanwu** [dokku/dokku-postgres#259]
I think postgres does support arm64/v8.
How to make the plugin support arm64/v8 as well?

**Comment by darkhelmet** [comment]
@kamanwu What was the solution to this? I am hitting this as well.

**Comment by darkhelmet** [comment]
Specifically, I'm hitting this when I'm trying to backup a database.

**Comment by darkhelmet** [comment]
I went into `/var/lib/dokku/plugins/enabled/postgres/config` and updated `PLUGIN_S3BACKUP_IMAGE` to `dokku/s3backup:0.13.0`

**Comment by josegonzalez** [comment]
These should all now be updated to use newer plugin versions that are arm/arm64 compatible (https://github.com/dokku/dokku-postgres/commit/90f6f1db08b4a24a406cf9919e3821250a2f3ee2).
