### ISSUE TITLE
Uploads to Minio fail with 'connection closed' error

### ISSUE THREAD

**Issue by nathlx** [dokku/dokku-postgres#266]
## Description of problem
Backup to new VM Minio server fails with error 
upload failed: - to s3://bucket/filename Connection was closed before we received a valid response from endpoint URL: "http://server:9000/bucket/filename".

Uploading files with cyberduck works correctly (after accepting selfsigned cert)

Is there a way to skip the certificate check for the backup?

### How reproducible
Setup a minio server, self sign TLS, add backup location, run backup

### Steps to Reproduce

1. dokku postgres:backup-auth app key secret region s3v4 http://server:9000
2.   postgres:backup app bucket

#### Actual Results
upload failed: - to s3://bucket/filename Connection was closed before we received a valid response from endpoint URL: "http://<server>:9000/bucket/filename".

#### Expected Results
Upload succeeds

## Environment Information

-----> uname: Linux servdokku 5.4.0-126-generic #142-Ubuntu SMP Fri Aug 26 12:12:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
                     total        used        free      shared  buff/cache   available
       Mem:           3931         700         140          29        3089        2920
       Swap:          3934           7        3927
-----> docker version: 
       Client: Docker Engine - Community
        Version:           20.10.17
        API version:       1.41
        Go version:        go1.17.11
        Git commit:        100c701
        Built:             Mon Jun  6 23:02:57 2022
        OS/Arch:           linux/amd64
        Context:           default
        Experimental:      true
       
       Server: Docker Engine - Community
        Engine:
         Version:          20.10.17
         API version:      1.41 (minimum version 1.12)
         Go version:       go1.17.11
         Git commit:       a89b842
         Built:            Mon Jun  6 23:01:03 2022
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.6.7
         GitCommit:        0197261a30bf81f1ee8e6a4dd2dea0ef95d67ccb
        runc:
         Version:          1.1.3
         GitCommit:        v1.1.3-0-g6724737
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info: 
       Client:
        Context:    default
        Debug Mode: true
        Plugins:
         app: Docker App (Docker Inc., v0.9.1-beta3)
         buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
         compose: Docker Compose (Docker Inc., v2.6.0)
         scan: Docker Scan (Docker Inc., v0.17.0)
       
       Server:
        Containers: 4
         Running: 4
         Paused: 0
         Stopped: 0
        Images: 45
        Server Version: 20.10.17
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Cgroup Version: 1
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 0197261a30bf81f1ee8e6a4dd2dea0ef95d67ccb
        runc version: v1.1.3-0-g6724737
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: default
        Kernel Version: 5.4.0-126-generic
        Operating System: Ubuntu 20.04.4 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 4
        Total Memory: 3.839GiB
        Name: phservdokku35
        ID: MKIM:EAYF:GWTY:DQQO:UTVI:U7PK:PYJS:4RJL:JSZZ:W225:RC3C:32TV
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false
       
-----> git version: git version 2.25.1
-----> sigil version: 0.9.0build+bc921b7
-----> herokuish version: 
       herokuish: 0.5.37
       buildpacks:
         heroku-buildpack-multi     v1.2.0
         heroku-buildpack-ruby      v244
         heroku-buildpack-nodejs    v198
         heroku-buildpack-clojure   v90
         heroku-buildpack-python    v214
         heroku-buildpack-java      v72
         heroku-buildpack-gradle    v38
         heroku-buildpack-scala     v94
         heroku-buildpack-play      v26
         heroku-buildpack-php       v223
         heroku-buildpack-go        v166
         heroku-buildpack-nginx     v16
         buildpack-null             v3
-----> dokku version: dokku version 0.27.10
-----> plugn version: plugn: 0.12.0build+3a27594
-----> dokku plugins: 
         00_dokku-standard    0.27.10 enabled    dokku core standard plugin
         20_events            0.27.10 enabled    dokku core events logging plugin
         app-json             0.27.10 enabled    dokku core app-json plugin
         apps                 0.27.10 enabled    dokku core apps plugin
         builder              0.27.10 enabled    dokku core builder plugin
         builder-dockerfile   0.27.10 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.27.10 enabled    dokku core builder-herokuish plugin
         builder-null         0.27.10 enabled    dokku core builder-null plugin
         builder-pack         0.27.10 enabled    dokku core builder-pack plugin
         buildpacks           0.27.10 enabled    dokku core buildpacks plugin
         certs                0.27.10 enabled    dokku core certificate management plugin
         checks               0.27.10 enabled    dokku core checks plugin
         common               0.27.10 enabled    dokku core common plugin
         config               0.27.10 enabled    dokku core config plugin
         cron                 0.27.10 enabled    dokku core cron plugin
         docker-options       0.27.10 enabled    dokku core docker-options plugin
         domains              0.27.10 enabled    dokku core domains plugin
         enter                0.27.10 enabled    dokku core enter plugin
         git                  0.27.10 enabled    dokku core git plugin
         logs                 0.27.10 enabled    dokku core logs plugin
         network              0.27.10 enabled    dokku core network plugin
         nginx-vhosts         0.27.10 enabled    dokku core nginx-vhosts plugin
         plugin               0.27.10 enabled    dokku core plugin plugin
         postgres             1.24.0 enabled    dokku postgres service plugin
         proxy                0.27.10 enabled    dokku core proxy plugin
         ps                   0.27.10 enabled    dokku core ps plugin
         registry             0.27.10 enabled    dokku core registry plugin
         repo                 0.27.10 enabled    dokku core repo plugin
         resource             0.27.10 enabled    dokku core resource plugin
         run                  0.27.10 enabled    dokku core run plugin
         scheduler            0.27.10 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.27.10 enabled    dokku core scheduler-docker-local plugin
         scheduler-null       0.27.10 enabled    dokku core scheduler-null plugin
         shell                0.27.10 enabled    dokku core shell plugin
         ssh-keys             0.27.10 enabled    dokku core ssh-keys plugin
         storage              0.27.10 enabled    dokku core storage plugin
         trace                0.27.10 enabled    dokku core trace plugin
=====> hrdb app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:             
=====> hrdb app information
       App created at:                1664503710
       App deploy source:             hrdb
       App deploy source metadata:    hrdb
       App dir:                       /home/dokku/hrdb
       App locked:                    false
=====> hrdb builder information
       Builder build dir:             
       Builder computed build dir:    
       Builder computed selected:     
       Builder global build dir:      
       Builder global selected:       
       Builder selected:              
=====> hrdb builder-dockerfile information
       Builder dockerfile computed dockerfile path: Dockerfile               
       Builder dockerfile global dockerfile path: Dockerfile               
       Builder dockerfile dockerfile path:                          
=====> hrdb builder-pack information
       Builder pack computed projecttoml path: project.toml             
       Builder pack global projecttoml path: project.toml             
       Builder pack projecttoml path:                          
=====> hrdb buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-20
       Buildpacks global stack:       
       Buildpacks list:               
       Buildpacks stack:              
=====> hrdb ssl information
       Ssl dir:                       /home/dokku/hrdb/tls     
       Ssl enabled:                   false                    
       Ssl hostnames:                                          
       Ssl expires at:                                         
       Ssl issuer:                                             
       Ssl starts at:                                          
       Ssl subject:                                            
       Ssl verified:                                           
=====> hrdb checks information
       Checks disabled list:          none                     
       Checks skipped list:           none                     
=====> hrdb cron information
       Cron task count:               0
=====> hrdb docker options information
       Docker options build:          --link dokku.postgres.testing:dokku-postgres-testing 
       Docker options deploy:         --link dokku.postgres.testing:dokku-postgres-testing --restart=on-failure:10 
       Docker options run:            --link dokku.postgres.testing:dokku-postgres-testing 
=====> hrdb domains information
       Domains app enabled:           true                     
       Domains app vhosts:           test.internal.psagroup.com
       Domains global enabled:        true                     
       Domains global vhosts:         internal.psagroup.com    
=====> hrdb git information
       Git deploy branch:             master                   
       Git global deploy branch:      master                   
       Git keep git dir:              false                    
       Git rev env var:               GIT_REV                  
       Git sha:                       bf7217c                  
       Git last updated at:           1664447647               
=====> hrdb logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:       
       Logs max size:                 
       Logs vector sink:              
=====> hrdb network information
       Network attach post create:           
       Network attach post deploy:           
       Network bind all interfaces:          false
       Network computed attach post create:  
       Network computed attach post deploy:  
       Network computed bind all interfaces: false
       Network computed initial network:     
       Network computed tld:                 
       Network global attach post create:    
       Network global attach post deploy:    
       Network global bind all interfaces:   false
       Network global initial network:       
       Network global tld:                   
       Network initial network:              
       Network static web listener:          
       Network tld:                          
       Network web listeners:                172.17.0.5:5000
=====> hrdb nginx information
       Nginx access log format:                                
       Nginx access log path:         /var/log/nginx/test-access.log
       Nginx bind address ipv4:                                
       Nginx bind address ipv6:       ::                       
       Nginx client max body size:                             
       Nginx disable custom config:   false                    
       Nginx error log path:          /var/log/nginx/test-error.log
       Nginx global hsts:             true                     
       Nginx computed hsts:           true                     
       Nginx hsts:                                             
       Nginx hsts include subdomains: true                     
       Nginx hsts max age:            15724800                 
       Nginx hsts preload:            false                    
       Nginx proxy buffer size:       4096                     
       Nginx proxy buffering:         on                       
       Nginx proxy buffers:           8 4096                   
       Nginx proxy busy buffers size: 8192                     
       Nginx proxy read timeout:      60s                      
       Nginx last visited at:         1666051200               
       Nginx x forwarded for value:   $remote_addr             
       Nginx x forwarded port value:  $server_port             
       Nginx x forwarded proto value: $scheme                  
       Nginx x forwarded ssl:                                  
=====> hrdb proxy information
       Proxy enabled:                 true
       Proxy port map:                http:80:5000
       Proxy type:                    nginx
=====> hrdb ps information
       Deployed:                      true
       Processes:                     1
       Ps can scale:                  true
       Ps computed procfile path:     Procfile
       Ps global procfile path:       Procfile
       Ps procfile path:              
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       true
       Status web 1:                  running (CID: 3ffc56ec558)
=====> hrdb registry information
       Registry computed image repo:      dokku/hrdb
       Registry computed push on release: false
       Registry computed server:          
       Registry global push on release:   
       Registry global server:            
       Registry image repo:               
       Registry push on release:          
       Registry server:                   
       Registry tag version:              
=====> hrdb resource information
=====> hrdb scheduler information
       Scheduler computed selected:   docker-local
       Scheduler global selected:     docker-local
       Scheduler selected:            
=====> hrdb scheduler-docker-local information
       Scheduler docker local disable chown:                          
       Scheduler docker local parallel schedule count:                          
=====> hrdb storage information
       Storage build mounts:                                   
       Storage deploy mounts:                                  
       Storage run mounts:

**Comment by josegonzalez** [comment]
Where is the domain name in that url? Thats probably why it can't connect.

**Comment by nathlx** [comment]
> Where is the domain name in that url? Thats probably why it can't connect.

Sorry I was using characters to mark variables and it hid them all. I've changed the formatting so the URL format should show now. 
Many thanks

**Comment by josegonzalez** [comment]
You said you added a self-signed cert? Why is the scheme there `http` then? I would also imagine that the awscli - which does the uploading - would error if there is a redirect or it can't validate the cert. Maybe its worth using something like letsencrypt instead for the certificate?

**Comment by nathlx** [comment]
> You said you added a self-signed cert? Why is the scheme there `http` then? I would also imagine that the awscli - which does the uploading - would error if there is a redirect or it can't validate the cert. Maybe its worth using something like letsencrypt instead for the certificate?

I can use the process in the MINIO docs to generate a tls for localhost, and then connect whilst ignoring the cert error from most clients. Since this is an internal server letsencypt is quite complex, needing DNS authentication etc. 
Is there a flag to ignore cert errors when running the upload?

**Comment by josegonzalez** [comment]
There isn't anything we configure for that. The underlying image is dokku/s3backup, which you can take a look at and fork to add some sort of support for this functionality. Pull requests welcome, but I'm not going to actively work on this.

**Comment by nathlx** [comment]
> There isn't anything we configure for that. The underlying image is dokku/s3backup, which you can take a look at and fork to add some sort of support for this functionality. Pull requests welcome, but I'm not going to actively work on this.

OK , will close the issue and test with a certificate. 
Thank you for the reply.
