### ISSUE TITLE
dokku postgres:export error

### ISSUE THREAD

**Issue by EfrSyn** [dokku/dokku-postgres#295]
I have a dokku with 5 Postgres databases.
They all work fine...

When I try to export one of the database:

dokku postgres:export synerp_db

I got:
pg_dump: error: connection to database "synerp_db" failed: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  database "synerp_db" does not exist

=====> synerp_db postgres service information
       Config dir:          /var/lib/dokku/services/postgres/synerp_db/data
       Config options:                               
       Data dir:            /var/lib/dokku/services/postgres/synerp_db/data
       Dsn:                 postgres://postgres:xxxxxx@dokku-postgres-synerp-db:5432/synerp_db
       Exposed ports:       -                        
       Id:                  36ddc269818af0a434f36027f7f044d65063aee029bd9e2e5448cd9c80b31d08
       Internal ip:         172.17.0.5               
       Initial network:                              
       Links:               synerp                   
       Post create network:                          
       Post start network:                           
       Service root:        /var/lib/dokku/services/postgres/synerp_db
       Status:              running                  
       Version:             postgres:13              

I checked all files in:
/var/lib/dokku/services/postgres/

Any idea?

Thanks a lot!

**Comment by josegonzalez** [comment]
Does that database actually exist in the service?

**Comment by EfrSyn** [comment]
Yes, the database exist and is filled with data. The only thing is that is has been created with the -C flag -C "USER=myuser"

**Comment by EfrSyn** [comment]
I'll have a look at the code...

connect give me an error: 
psql: error: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  database "synerp_db" does not exist

But I have exposed temporarly the database and I was able to connect to it from my Postgres client...

So, that's strange...

Thank you for your help!

**Comment by josegonzalez** [comment]
Yeah so thats interesting, and leads me to believe that somehow the database you are saying exists does not actually exist.

Since its exposed remotely, can you try the equivalent psql command [here](https://github.com/dokku/dokku-postgres/blob/master/functions#L21), slotting in the `DATABASE_NAME` as `synerp_db`?

**Comment by EfrSyn** [comment]
Hello, I found the problem :) The application connected to this database created a new database with another name. So, I changed the content of DATABASE_NAME in /var/lib/dokku/services/postgres/synerp_db and it works now! :) 

Again thank you for your help :)
