### ISSUE TITLE
pgvector for Vector Similarity Search

### ISSUE THREAD

**Issue by MiKatre** [dokku/dokku-postgres#305]
Hi,

I am building an app that relies heavily on vector similarity searches. I plan to use Postgres along with the `pgvector` extension for this purpose. I was wondering if it's possible to install the `pgvector` extension in `dokku-postgres`, so that I can deploy using Dokku.

(For context, `pgvector` is an open-source extension that enables vector similarity search within Postgres.)

Thanks !

**Comment by Schlepptop** [comment]
You can use any custom image for your postgres service:

dokku postgres:create your-database --image "your/image" --image-version "1.0.0"


MiKatre ***@***.***> schrieb am Mi., 20. Sept. 2023, 22:59:

**Comment by MiKatre** [comment]
Very cool, I misunderstood how `—image` worked by reading the doc too fast. That means I can just use the `ankane/pgvector` image.  

That solves the problems, thanks @Schlepptop !

**Comment by amitkot** [comment]
The updated pgvector image now is `pgvector/pgvector`, so the updated command (with `pg17`) is:

```shell
dokku postgres:create your-database --image "pgvector/pgvector" --image-version "pg17"
```
