### ISSUE TITLE
Postgresql configuration

### ISSUE THREAD

**Issue by g-normand** [dokku/dokku-postgres#316]
Hello,
I would like to get information about the requests that are really long to optimize them.
Is it possible to modify the Postgresql configuration?

I wanted to add 
`
log_statement = 'all'
`
`
log_duration = on
`
`
log_min_duration_statement = 5000 
`

I saw that there is a command ` postgres:set <service> <key> <value> `  but it doesn't seems to be helpful for my case.
What would be the best practice?

Thanks
Guillaume

**Comment by Schlepptop** [comment]
You can `dokku postgres:enter` the container, modify the config file
directly and then `dokku postgres:restart` the DB.
Entering is not strictly necessary, you can also modify the file from where
it is mounted (somewhere in /var/lib/dokku/), but I don't remember the
exact path.

**Comment by g-normand** [comment]
Thanks!

I could change this way:
```
dokku postgres:enter service

sed -i "s/^#log_statement = 'none'/log_statement = 'all'/" /var/lib/postgresql/data/postgresql.conf
sed -i "s/^#log_duration = off/log_duration = on/" /var/lib/postgresql/data/postgresql.conf
sed -i "s/^#log_min_duration_statement = -1/log_min_duration_statement = 5000/" /var/lib/postgresql/data/postgresql.conf

dokku postgres:restart service
dokku ps:restart app
dokku postgres:logs service
```

now it's logging, but I have all requests and not the one I'm looking for (more than 5sec only). I will continue my search.
