### ISSUE TITLE
Could not get container for Postgres - no such container

### ISSUE THREAD

**Issue by jimmypoulsen** [dokku/dokku-postgres#335]
## Description of problem
I recently changed the database of one of my applications. I did that by:
1. Unlinking the old database (my-staging-db) from my application
2. Linking the new database (my-staging-db2) to my application

Everything seemed to work fine until today where I decided to delete the old database (my-staging-db) as I don't need it anymore. But then I suddenly started getting these errors:

```
 !     Failed to create release execution container: Error response from daemon: could not get container for dokku.postgres.my-staging-db: No such container: dokku.postgres.my-staging-db
```

My config's `DATABASE_URL` points to my new database (my-staging-db2). When I do `dokku postgres:links my-staging-db2` I also get my application back.

Doing `dokku postgres:links my-staging-db` obviously returns ` !     Postgres service my-staging-db does not exist` as that is now deleted.

I did manage to get my build working by creating a new database with the old database's name.

After that I did some more digging and I found out that the Docker options for my application still had the link to the old database. I couldn't remove it with `dokku docker-options:remove staging deploy "--link dokku.postgres.my-staging-db:dokku-postgres-my-staging-db"` so I had to manually go and edit the `DOCKER_OPTIONS_DEPLOY` file. Doing that seems to have resolved my issue.

### Steps to Reproduce

1. Link database to application
2. Unlink database from application
3. Create new database
4. Link new database to application
5. Destroy old database

#### Actual Results
Postgres link wasn't removed for my application's docker deploy options

#### Expected Results
Postgres link removed from everywhere

### `dokku report APP_NAME` output

```
=====> staging docker options information
       Docker options build:          --link dokku.postgres.my-staging-db2:dokku-postgres-my-staging-db2 --link dokku.redis.my-staging-redis:dokku-redis-my-staging-redis
       Docker options deploy:         --add-host=host.docker.internal:host-gateway --link dokku.postgres.my-staging-db:dokku-postgres-my-staging-db --link dokku.redis.my-staging-redis:dokku-redis-my-staging-redis --link dokku.postgres.my-staging-db2:dokku-postgres-my-staging-db2 --restart=on-failure:10
       Docker options run:            --add-host=host.docker.internal:host-gateway --link dokku.postgres.my-staging-db2:dokku-postgres-my-staging-db2 --link dokku.redis.my-staging-redis:dokku-redis-my-staging-redis
```

**Comment by josegonzalez** [comment]
This is weird because the unlink should be removing the database link for sure. There's a test for that and everything. Are you positive it actually unlinked and didn't somehow error out?

**Comment by jimmypoulsen** [comment]
Unfortunately I don't have anything that I can prove here but I'm sure I did that and it succeeded. Also, wouldn't my `postgres:destroy` cause an error if it was linked to an application?

**Comment by josegonzalez** [comment]
No because we dont check the downstream services for links: https://github.com/dokku/dokku-postgres/blob/master/subcommands/destroy#L25

I wonder if maybe it was removed from the LINKS file first and then the removal of the option failed? Did you maybe link the new db first?

**Comment by jimmypoulsen** [comment]
That's definitely a possibility .. Thank you for the quick response. I'll do some testing the next couple of days and then I'll get back with my discoveries (if any) :smile:
