### ISSUE TITLE
Cannot dump database through SSH

### ISSUE THREAD

**Issue by ebeigarts** [dokku/dokku-postgres#36]
We are having problems importing the custom format dump using `pg_restore` on other machines - `Segmentation fault (core dumped)`

I think the default should be plain sql (this is also what pg_dump does by default) and maybe somehting like `dokku postgres:export <app> -Fc` could dump in the custom format.

WDYT?

Our current workaround is `ssh root@<host> "docker exec dokku.postgres.<app> env PGPASSWORD=<pw> pg_dump --no-acl --no-owner -h localhost -U postgres -w <app>"`

**Comment by josegonzalez** [comment]
@Flink thoughts here?

**Comment by Flink** [comment]
I need to do some tests but I never dumped (nor restored) in plain SQL with PG and I never had any problems. (and I migrated data from Heroku to “real” PG servers, to containers, etc., it always worked). It might be a problem on your machines or maybe with a certain version of PG, I don’t know.

@ebeigarts Did you try to dump/restore directly on the machine and not through ssh? (just an idea)

**Comment by ebeigarts** [comment]
@Flink it works locally on the machine. `ssh -t` / `RequestTTY yes` was [the problem](http://unix.stackexchange.com/questions/151916/why-is-this-binary-file-transfered-over-ssh-t-being-changed) and this is the way [dokku recommends](http://progrium.viewdocs.io/dokku/remote-commands/). Using `ssh -T dokku@<host> -- postgres:export <app>` works. Using plain SQL dumps this wasn't a problem. Maybe there should be a warning in the README about this?

**Comment by ebeigarts** [comment]
Maybe the `postgres:export` command could check if it is running in a tty and print a warning to stderr?

```
$ ssh -T root@<host> 'echo $SSH_TTY'

$ ssh -t root@<host> 'echo $SSH_TTY'
/dev/pts/4
Connection to dokku.makit.lv closed.
```

**Comment by Flink** [comment]
I think I had a similar problem on https://github.com/Flink/dokku-psql-single-container, I’ll take a look about what you’re suggesting :)

**Comment by josegonzalez** [comment]
https://github.com/dokku/dokku-postgres/pull/19 @Flink maybe related?

**Comment by Flink** [comment]
Maybe we need to check for the tty yeah, I don’t know. I’ll do some testing :)
