### ISSUE TITLE
Environment Variables Do Not Get Generated

### ISSUE THREAD

**Issue by firrae** [dokku/dokku-postgres#38]
Hello,

After installing the plugin and creating a database for my Ghost blog I checked the config on the blog's container to find only DATABASE_URL has been set after linking the blog's database and the blog's container. I'm not sure if I missed something, but I followed the instructions in the readme.

If you need more info please let me know:
dokku version: 0.4.2
postgres : 9.4.4

**Comment by josegonzalez** [comment]
Are you sure you are using dokku 0.2.4?

What other environment variables are you expecting that are missing?

**Comment by Flink** [comment]
As documented in the README, only `DATABASE_URL` is exported so it’s perfectly normal.
You don’t need anything else for Ghost, I have this in my `config.js`:
```javascript
…
        database: {
            client: 'postgres',
            connection: process.env.DATABASE_URL,
            debug: false
        },
…
```

**Comment by firrae** [comment]
@josegonzalez Apparently I'm dyslexic at 1am, it's 0.4.2

@Flink I'll try that as soon as I get home, I had tried it before, but I think I may have used pg instead of postgres as the client.

**Comment by firrae** [comment]
Though with the readme "the above will expose the following environment variables" and then lists DOKKU_POSTGRES_LOLIPOP_NAME, DOKKU_POSTGRES_LOLIPOP_PORT, DOKKU_POSTGRES_LOLIPOP_PORT_5432_TCP, etc. Are these then global? These didn't seem to show up there either. Maybe I'm misunderstanding the documentation?

**Comment by firrae** [comment]
@Flink Your config seems to have worked, once I've figured out a good theme I'll let you know if it actually has after I upload it.

**Comment by Flink** [comment]
@firrae ah yes sorry, those variables are automatically exported by docker when linking containers between them. So you won’t see them with `dokku config` but you can see that the container has them by doing something like `dokku run <app> env` :)

**Comment by josegonzalez** [comment]
@Flink mind adding documentation to the readme's regarding the docker linked env vars?

**Comment by firrae** [comment]
@Flink that seems to have fixed it, thanks a bunch for pointing that out! Should I close this or should I leave that to you guys?

**Comment by Flink** [comment]
@josegonzalez nope, will do ;)

@firrae you’re welcome and yes you can close this :)
