### ISSUE TITLE
How do you connect remotely to a database?

### ISSUE THREAD

**Issue by MauriceZ** [dokku/dokku-postgres#42]
It is possible to configure this plugin so that it's possible to connect to postgres remotely?

Same issue as for this plugin that was solved: https://github.com/Flink/dokku-psql-single-container/issues/10

Thanks!

**Comment by Flink** [comment]
There is a `postgres:expose` command for this :)

**Comment by MauriceZ** [comment]
Oh...

I doubled checked the command list so many times too to make sure I wasn't
missing it :S.

Thanks!

**Comment by Flink** [comment]
No problem, you’re welcome :)

**Comment by josegonzalez** [comment]
@Flink is expose/unexpose documented for each plugin?

**Comment by Flink** [comment]
@josegonzalez not explicitly I think
