### ISSUE TITLE
Cannot delete linked service

### ISSUE THREAD

**Issue by duboff** [dokku/dokku-postgres#43]
When I delete the app, deleting a postgres service seems impossible. Always get the "Cannot delete linked service". Tried running unlink but still get the message. Is there any way to force deletion?

**Comment by josegonzalez** [comment]
You have it linked to a running application, are you sure you unlinked it?

**Comment by duboff** [comment]
Yeah, what happened was I destroyed the app first. So now the db is orphaned. I tried linking it to a different app, unlinking and destroying but still get the same message.

**Comment by duboff** [comment]
I guess the real problem is that when the app is deleted, postgres service stays in place

**Comment by josegonzalez** [comment]
Gotcha. I guess that is something we can fix in the plugin. Thanks for confirming the workflow issue!

**Comment by Flink** [comment]
Well that’s strange since there is already a hook that unlinks an app from a service when deleting the app.
