### ISSUE TITLE
postgres:export exit status 1

### ISSUE THREAD

**Issue by ukasiu** [dokku/dokku-postgres#45]
`dokku postgres:export dbname` exits with 1 despite successful dump.

**Comment by josegonzalez** [comment]
Can you provide the output of the command (sans dump) with `DOKKU_TRACE=1`?

**Comment by ukasiu** [comment]
complete stderr: http://pastebin.com/qXQ3pwQP

**Comment by josegonzalez** [comment]
Fixed by #57
