### ISSUE TITLE
single container?

### ISSUE THREAD

**Issue by sglebs** [dokku/dokku-postgres#49]
Please detail in the Readme how to do a single container scenario, like https://github.com/Flink/dokku-psql-single-container/issues/19 does. Thanks!

**Comment by josegonzalez** [comment]
Relevant PR discussion: https://github.com/dokku/dokku-postgres/pull/44

**Comment by josegonzalez** [comment]
Will track all the work related to this here: #35.

**Comment by josegonzalez** [comment]
See dokku/dokku-redis/issues/64 for more information.
