### ISSUE TITLE
rake db:drop / rake db:purge results in ActiveRecord::StatementInvalid: PG::ObjectInUse

### ISSUE THREAD

**Issue by hhff** [dokku/dokku-postgres#51]
Hi!

For some reason, whenever I run `rake db:drop` or `rake db:purge` on my staging app, I get:
```
ActiveRecord::StatementInvalid: PG::ObjectInUse: ERROR:  database "staging" is being accessed by other users
DETAIL:  There are 18 other sessions using the database.
```

Weirdly enough, `rake db:reset` works fine.  Any thoughts? :heart:

**Comment by hhff** [comment]
It's also kinna whack because there's 18 sessions using the db - but this is a staging box, and there's almost definitely no traffic there :confused:

**Comment by josegonzalez** [comment]
Your rails app is probably still using it's connections?

**Comment by hhff** [comment]
18 "sessions" seems like a lot for a staging box that is not being hit at all though right?

**Comment by josegonzalez** [comment]
> Your rails app is probably still using it's connections?

Rails will hold connections open since the processes just sit around, no?

**Comment by hhff** [comment]
hmm ok.  I'm just using the most boilerplate rails / postgres / dokku setup.  How would you recommend doing `db:drop` wtih rails holding open these connections?

**Comment by hhff** [comment]
I guess something like this?  https://www.krautcomputing.com/blog/2014/01/10/how-to-drop-your-postgres-database-with-rails-4/

Just seems strange that there's these 18 dangling sessions.  Is it possible old dokku containers (versions of the app) are holding open their connections to the DB ?

**Comment by josegonzalez** [comment]
Stop your rails app and then run `db:drop`?

Old dokku containers are retired after a minute or so, but you can check on whats running via `docker ps -a`. You should also check the postgres processlist to see what the actual clients are that have running connections, and then trace them back to the containers that are running. I'm 100% sure it's just rails being stupid, and will buy you a hot dog if thats not the case.

**Comment by hhff** [comment]
word thankyou @josegonzalez - will report back :hamburger:

**Comment by josegonzalez** [comment]
:fire: :dog2:

**Comment by arielscherman** [comment]
I am having a related issue (using `Rails 5.1.`). Any news?

I am running:

```ruby
ActiveRecord::Tasks::DatabaseTasks.purge("my_app_test")
```

And I get this:

> /my-folder/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:73:in `async_exec': PG::ObjectInUse: ERROR:  database "my_app_test" is being accessed by other users (ActiveRecord::StatementInvalid)
DETAIL:  There is 1 other session using the database.
: DROP DATABASE IF EXISTS "my_app_test"

**Comment by josegonzalez** [comment]
@arielscherman this isn't a Dokku-related issue, but something to do with your application running. Rails keeps a persistent connection. You'll need to scale your app down if you want to drop the database it seems.

A simple google of your error (without referencing your database name) resulted in the following: https://stackoverflow.com/questions/2369744/rails-postgres-drop-error-database-is-being-accessed-by-other-users

Also, please avoid commenting on 2+ year old issues. It notifies folks who may no longer even be using the project. In the future, please open a new issue instead and reference this one.
