### ISSUE TITLE
PostGIS Extension?

### ISSUE THREAD

**Issue by willcodeforfoo** [dokku/dokku-postgres#52]
Is it possible to get the PostGIS extension working in a database?

I tried running `create extension postgis;` and got the following error:
    
    ERROR:  could not open extension control file "/usr/share/postgresql/9.4/extension/postgis.control": No such file or directory`

I suppose if you could somehow use the [mdillon/postgis](https://hub.docker.com/r/mdillon/postgis/) Docker image instead of the official Postgres one it'd work. Is it possible to somehow override `POSTGRES_IMAGE` in the config?

**Comment by Flink** [comment]
If the `postgis` image is compatible with the official one, then yeah it should work.
As explained in the README, you just have to define those env var:
```bash
export POSTGRES_IMAGE="postgres"
export POSTGRES_IMAGE_VERSION="9.4.4"
```

**Comment by pythdasch** [comment]
I'm very interested about this issue because I'm block with postgis. I tried the other plugins but they aren't fully compatible with the new dokku version... how could I resolve this ?

**Comment by sethdeckard** [comment]
@pythdasch, I was able to get this working using the postgis Docker image @willcodeforfoo mentions above, just install the Docker image you want (here's what I have currently):

mdillon/postgis                   latest              f277f6afdf67        2 weeks ago         431.5 MB
mdillon/postgis                   9.4                 709cb883439d        2 weeks ago         431.5 MB

Then just change the two ENV vars mentioned in the docs to point to an installed PostGIS image and you should be good to use the plugin to create new database containers.

**Comment by pythdasch** [comment]
Ok I'll try then, thx for the tips :)

**Comment by willcodeforfoo** [comment]
@sethdeckard Thanks! Dumb question, where should I set those ENV vars?

**Comment by pythdasch** [comment]
Good question @willcodeforfoo what is the workflow to achieve what you did ?

**Comment by sethdeckard** [comment]
@willcodeforfoo, You can set them per session or permanently via /etc/environment.

**Comment by sethdeckard** [comment]
@pythdasch, Use the docker command to pull the image you want:  

(sudo) docker pull mdillon/postgis:latest

Then just set your env vars:

export POSTGRES_IMAGE="mdillon/postgis"
export POSTGRES_IMAGE_VERSION="latest"

**Comment by pythdasch** [comment]
Thx @sethdeckard I did all of this in my dokku (I'm with digitalocean) but I'm stuck after : 
Must I create a database with postgres:create or not? because when I try to link my app to mdillon/postgis image it says that the service doesn't exist. thx for your patience

**Comment by sethdeckard** [comment]
Yes, you must create your database with the plugin (postgres:create), the ENV vars are used by it to know which postgres image to use when creating your container.

**Comment by pythdasch** [comment]
DAMN it !!! I did it !!! Thanks a lot @sethdeckard :)

**Comment by josegonzalez** [comment]
You can't list a service that isn't created ;)

**Comment by pythdasch** [comment]
Hi I'm having issue with this trick because of :  Error parsing reference: "mdillon/postgis\" :9.5.2" is not a valid repository/tag.

**Comment by pythdasch** [comment]
I trried also latest but fails also :(

**Comment by pythdasch** [comment]
it's ok I did it !

**Comment by sebastiangraef** [comment]
Because I just spent some time on this, I had to run:
```
dokku postgres:connect APP
```
and
```
CREATE EXTENSION postgis;
```
to get this to work.

**Comment by wyozi** [comment]
FYI postgis has an official docker image you can use now: `postgis/postgis`
