### ISSUE TITLE
Rails 4 + Dokku - URI::InvalidURIError (DATABASE_URL config incorrect)

### ISSUE THREAD

**Issue by twanlass** [dokku/dokku-postgres#53]
Ubuntu 14.04
Rails 4 (4.2.4)
Dokku 0.4.9
Docker 1.9.1
Dokku-postgres latest (`master`)

When creating and then attempting to link a new database I'm getting the following error:
`the scheme postgres does not accept registry part: root:password@: (or bad hostname?) (URI::InvalidURIError)`

The resulting app config `DATABASE_URL` looks malformed:
`postgres://root:password@:/db`

While the app config `DOKKU_POSTGRES_..._URL` looks correct:
postgres://postgres:[...]@dokku-postgres-api:5432/api

In fact, changing the  `DATABASE_URL` to use the generated `DOKKU_POSTGRES_..._URL` seems to work. 

Was there a recent change maybe that broke this? What else can I provide that may help iron this out?

Thanks for the awesome plugin!

**Comment by josegonzalez** [comment]
You may have manually set that `DATABASE_URL` there, since we don't use the `root` user. If you already have that env var from somewhere else, then we don't override it and you need to call `postgres:promote` (same as heroku).

**Comment by josegonzalez** [comment]
Can you list your installed plugins?

**Comment by twanlass** [comment]
@josegonzalez - yup, I think that's it. I'm migrating from another Postgres plugin (https://github.com/Kloadut/dokku-pg-plugin).

Thanks!

For posterity:
```
  00_dokku-standard    0.4.0 enabled    dokku core standard plugin
  20_events            0.4.0 enabled    dokku core events logging plugin
  api                  0.2.0 enabled    support for pre- and post-deploy hooks
  apps                 0.4.0 enabled    dokku core apps plugin
  backup               0.4.0 enabled    dokku core backup plugin
  build-env            0.4.0 enabled    dokku core build-env plugin
  certs                0.4.0 enabled    dokku core certificate management plugin
  checks               0.4.0 enabled    dokku core checks plugin
  common               0.4.0 enabled    dokku core common plugin
  config               0.4.0 enabled    dokku core config plugin
  deploy-hooks         0.2.0 enabled    support for pre- and post-deploy hooks
  docker-options       0.4.0 enabled    dokku core docker-options plugin
  domains              0.4.0 enabled    dokku core domains plugin
  enter                0.4.0 enabled    dokku core enter plugin
  git                  0.4.0 enabled    dokku core git plugin
  logs                 0.4.0 enabled    dokku core logs plugin
  named-containers     0.4.0.1 enabled    dokku core named containers plugin
  nginx-vhosts         0.4.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.4.0 enabled    dokku core plugin plugin
  postgres             1.0.0 enabled    dokku postgres service plugin
  ps                   0.4.0 enabled    dokku core ps plugin
  shell                0.4.0 enabled    dokku core shell plugin
  tags                 0.4.0 enabled    dokku core tags plugin
  tar                  0.4.0 enabled    dokku core tar plugin
```

**Comment by josegonzalez** [comment]
Heh yeah, glad its settled and the new plugin is serving you well :)
