### ISSUE TITLE
Postgres image postgres:9.5.0 not found

### ISSUE THREAD

**Issue by duboff** [dokku/dokku-postgres#55]
I might be missing something, but I updated dokku and the the plugin (through *dokku plugin:update postgres*) but can't upgrade the database to 9.5.0 or create a new Postgres service for that matter getting this error:

```sh
~# dokku postgres:create db
Postgres image postgres:9.5.0 not found
```
Is there anything else I need to do to pull in the latest version of PG?

**Comment by josegonzalez** [comment]
You need to `docker pull` the image.

**Comment by duboff** [comment]
@josegonzalez, thanks. Is there a guide on doing that? Want to avoid destroying my db

**Comment by josegonzalez** [comment]
That won't destroy a database, it just pulls an image.

```
docker pull postgres:9.5.0
```

**Comment by duboff** [comment]
Thanks, that indeed works. For the record just doing
```sh
docker pull postgres
```
Doesn't

**Comment by treythomas123** [comment]
Would you be open to a PR that would automatically `docker pull` the image if it's not found locally?

**Comment by josegonzalez** [comment]
Sure, just make the pr to every repo as well.
