### ISSUE TITLE
set database connection pool in URL

### ISSUE THREAD

**Issue by Sailias** [dokku/dokku-postgres#56]
Rails allows the DATABASE_URL to look like

```
postgresql://localhost/blog_development?pool=5
```

I don't see any query string params able to be appended to the DATABASE_URL when linking.
https://github.com/dokku/dokku-postgres/blob/2d6684d6e3323e9fda8ff39d01f6344a6ab7929c/functions#L269

Is there a way to set the database_pool in the DATABASE_URL at the moment?

**Comment by josegonzalez** [comment]
No, not at the moment.

**Comment by josegonzalez** [comment]
We should take care of this at the link level. For instance, here is what we could do:

```
dokku postgres:link SERVICE APP --querystring "pool=5"
```

We'd need to store these on disk for each link. I don't think it makes sense to have both "service-level" and "link-level" querystring arguments, as then we need to deal with merging/overwriting.

**Comment by josegonzalez** [comment]
Closing in favor of a rather large rfc here: dokku/dokku-redis/issues/64
