### ISSUE TITLE
Can't destroy a service

### ISSUE THREAD

**Issue by duboff** [dokku/dokku-postgres#58]
So I was trying to move to Postgres 9.5 as per instruction. What I want to do now is to destroy the old service and rename the new one back to the name the old one had. But even though the service is stopped and unlinked I can't fully destroy it.

``` sh
root@xxx:~# dokku postgres:destroy app
 !     WARNING: Potentially Destructive Action
 !     This command will destroy app Postgres service.
 !     To proceed, type "app"

> app
-----> Deleting app
-----> Stopping container
Error response from daemon: no such id: dokku.postgres.app
Error: failed to stop containers: [dokku.postgres.app]
```

This is probably related:

``` sh
root@chattermill:~# dokku postgres:list
Error: No such image or container: dokku.postgres.app
Error: No such image or container: d53ff2c50a7b2e4663501aa4e29dd052a0384a170af52d6a139180cd4363f210
Error: No such image or container: d53ff2c50a7b2e4663501aa4e29dd052a0384a170af52d6a139180cd4363f210
Error: No such image or container: d53ff2c50a7b2e4663501aa4e29dd052a0384a170af52d6a139180cd4363f210
Error: No such image or container: d53ff2c50a7b2e4663501aa4e29dd052a0384a170af52d6a139180cd4363f210
Error: No such image or container: d53ff2c50a7b2e4663501aa4e29dd052a0384a170af52d6a139180cd4363f210
NAME     VERSION       STATUS   EXPOSED PORTS  LINKS
app      stopped       -        -
app_9_5  postgres:9.5  running  5432->5432     app
```

Could be related to the previous issue I had in #43

**Comment by tomsabin** [comment]
Interestingly I had the same problem but managed to resolve it by starting the service again, and then destroying it when it was running.

**Comment by duboff** [comment]
Confirm that starting and destroying indeed works in some cases. In one I had to start, kill container and then destroy.

**Comment by josegonzalez** [comment]
If someone can get me into a state where I can reproduce this, I'd be happy to fix it once and for all :)

**Comment by duboff** [comment]
Sorry for radio silence. Unfortunately, it's hard to reproduce. It seems that the bug itself was probably fixed in one of the later versions but you still have a problem with services created in previous versions.

I would close for now and see if it reappears.

**Comment by josegonzalez** [comment]
Cool thanks. Feel free to comment if you know how to repro :)
