### ISSUE TITLE
Set postgres image/version with postgres:create option

### ISSUE THREAD

**Issue by treythomas123** [dokku/dokku-postgres#61]
I know you can choose a non-default postgres version like this:

```
POSTGRES_IMAGE_VERSION=9.4 dokku postgres:create <name>
```

But I usually use the dokku shell through SSH, and I don't see a way to set the postgres version when running like this. I'd like to be able to do the following:

```
ssh dokku@hostname postgres:create <name> -v 9.4
```

or maybe this way, to also support different images:
```
ssh dokku@hostname postgres:create <name> -i postgres:9.4
```

Is there a way to do this already that I'm not seeing? Or would you be open to a PR to add this option?

**Comment by josegonzalez** [comment]
No way to do it atm. If you want this feature, you're gonna have to build it for us.

**Comment by josegonzalez** [comment]
The proposal for this is available in this issue comment: https://github.com/dokku/dokku-mongo/issues/37#issuecomment-243014116

**Comment by josegonzalez** [comment]
See dokku/dokku-redis/issues/64 for more information.

**Comment by josegonzalez** [comment]
This is now implemented.
