### ISSUE TITLE
Raising work_mem in Dokku Postgres ? 

### ISSUE THREAD

**Issue by stanislasdrg** [dokku/dokku-postgres#69]
Hello everybody,
is editing the postgresql.conf file in /var/lib/dokku/services/postgres/appName/data the proper way of raising work_mem ?
I noticed there was a postgresql.auto.conf file in the same directory. However the latest is auto generated.

Thank you for your help.

S.

**Comment by josegonzalez** [comment]
Yes, you can edit it and restart your postgres database. That directory is mounted as config for the postgres plugin, so it'll pick it up.
