### ISSUE TITLE
Digital Ocean Block Storage & Dokku postgres

### ISSUE THREAD

**Issue by stanislasdrg** [dokku/dokku-postgres#78]
Hello,
as you might have seen, Digital Ocean introduced [block storage](https://www.digitalocean.com/community/tutorials/how-to-use-block-storage-on-digitalocean), which is very valuable for people who have huge storage needs.
I was wondering how I could possibly implement block storage in an already running Dokku configuration ?
As block storage acts as a casual attached volume, my question is more :  can I transfer a dokku-postgres DB to another volume ? What would be the steps to take in order to achieve this, assuming it's possible ?
I saw Dokku's persistent storage plugin, and was wondering whether this would be the way to go..

Thank you for your help.

**Comment by siavashs** [comment]
Hi,

Dokku uses Docker to run postgres instances, all images and volumes are located under `/var/lib/docker`. You can take the following steps to transfer all Docker data to a block storage:

1. Stop all Dokku apps
2. Stop Docker daemon
3. Mount the block storage under a temporary path, for example: `/mnt/block`
4. `mv /var/lib/docker/* /mnt/block/`
5. `umount /mnt/block`
6. Add a `fstab` entry for the block storage to mount it under `/var/lib/docker`
7. `mount /var/lib/docker`
8. Check if it is mounted
9. Start Docker daemon
10. Start Dokku apps

**Comment by josegonzalez** [comment]
Note: the data for our volumes is actually stored in `/var/lib/dokku/services/postgres/SERVICE_NAME/data`. You should mount the `/var/lib/dokku/services` directory instead.

**Comment by stanislasdrg** [comment]
Sorry to spam you guys, but I thought I'd write the steps here for future reference.
So here is what I did :

**Comment by ohld** [comment]
sorry to resurrect the old issue, but maybe you can help:

I'm using Dokku's Postgres plugin on DigitalOcean droplet with 160GB disk. I want to expand the disk using DO's block storage but I'm not sure if that is even possible. I want to leave my current Postgres data as is and just attach more volume.

Is it possible to attach DigitalOcean's block storage to already created Dokku's Postgres? So just to enlarge the space for Postgres needs.

**Comment by josegonzalez** [comment]
@ohld this might be better suited as a question to Digitalocean support, as it's not directly related to the plugin. You could also try our [github discussions](https://github.com/dokku/dokku/discussions).
