### ISSUE TITLE
Permission denied when trying to link db with app with Dokku 0.7.0

### ISSUE THREAD

**Issue by inket** [dokku/dokku-postgres#79]
Any idea what might be the cause for this?

```bash
$ dokku postgres:link dbname appname
/var/lib/dokku/plugins/available/docker-options/functions: line 82: /home/dokku/appname/DOCKER_OPTIONS_DEPLOY: Permission denied
```
I'm using Dokku 0.7.0

**Comment by inket** [comment]
`/home/dokku/appname/DOCKER_OPTIONS_DEPLOY` was `root:root` for some reason. A simple `chown` fixed it. It's obviously unrelated to dokku-postgres. Sorry!

**Comment by iandees** [comment]
I also ran into this when trying to link a Redis image to my app. To be specific, the line that will fix it is:

```
chown dokku:dokku /home/dokku/appname/DOCKER_OPTIONS_DEPLOY
```

Replace `appname` in there with the name of your app.
