### ISSUE TITLE
Using local psql to connect to DB?

### ISSUE THREAD

**Issue by siavashs** [dokku/dokku-postgres#80]
As I checked this plugin uses the following command when you run `dokku postgres:connect`:
```
docker exec -i $SERVICE_TTY_OPTS "$SERVICE_NAME" psql -h localhost -U postgres "$DATABASE_NAME"
```
Out ream does not like it because of it's limitations (limited number of lines, no search functionality, etc.)

I think it would be better if the plugin installs and uses a local psql command from the host, passing the credentials from DATABASE_URL.

I would be happy to implement this but would like to know your thoughts.

**Comment by josegonzalez** [comment]
If you want to use a different psql command, you're going to have to do that on your own. Our goal with the official plugins is to push as much of the functionality as possible into docker container calls.

Is there a reason the limitations cannot be worked around with the existing call?

**Comment by siavashs** [comment]
I think the limitations are actually Docker tty limitations, so not sure if they can be worked around.

**Comment by josegonzalez** [comment]
If you need a more enhanced postgres client, I would suggest using a local `psql` or other and running `postgres:expose` on your postgres database.

**Comment by siavashs** [comment]
A quick dirty workaround in case someone is interested:

```bash
#!/bin/bash

NAME=$1
IP=`docker inspect dokku.postgres.$NAME | python -c 'import json,sys;obj=json.load(sys.stdin);print obj[0]["NetworkSettings"]["Networks"]["bridge"]["IPAddress"]'`
DATABASE_URL=`dokku config:get $NAME DATABASE_URL`
USERNAME=`echo $DATABASE_URL | sed "s/[a-z]*:\/\/\([a-zA-Z0-9]*\):.*/\1/"`
PASSWORD=`echo $DATABASE_URL | sed "s/[a-z]*:\/\/[a-zA-Z0-9]*:\([a-z0-9]*\)@.*/\1/"`
PORT=`echo $DATABASE_URL | sed "s/[a-z]*:\/\/[a-zA-Z0-9]*:[a-z0-9]*@.*:\([0-9]*\)\/.*/\1/"`
DATABASE=`echo $DATABASE_URL | sed "s/[a-z]*:\/\/[a-zA-Z0-9]*:[a-z0-9]*@.*:[0-9]*\/\(.*\)/\1/"`

PGPASSWORD=$PASSWORD /usr/bin/psql -h $IP -p $PORT -U $USERNAME $DATABASE
```
Requires `psql` to be installed on host machine.
