### ISSUE TITLE
Can't unlink service if not configured for the app

### ISSUE THREAD

**Issue by eisensheng** [dokku/dokku-postgres#82]
The command `postgres:unlink` won't complete successfully if the given database is not configured in the environment/config space for the given application. This can happen because the key in question holding the database connection string already holds a different value.

Setting the database's connection string for the given application again allows the command to complete successfully.

This is troublesome because `postgres:destroy` won't succeed either because the link between the database and the app is still present though. Both commands don't make it clear that this is the problem either.

**Comment by josegonzalez** [comment]
Can you provide steps to replicate, this, as well as `--trace` output of the problematic `postgres:unlink` call?

**Comment by josegonzalez** [comment]
@eisensheng *bump*

**Comment by josegonzalez** [comment]
Closing as there hasn't been an update in over a month.
