### ISSUE TITLE
[Question] PostgreSQL Replication using Dokku

### ISSUE THREAD

**Issue by FilipLukac** [dokku/dokku-postgres#88]
Hello, is there any option to use LoadBalancing / Replication PostgreSQL Under dokku ?

**Comment by josegonzalez** [comment]
Nope, and it's not on any roadmap either. If you'd like to sponsor the work around that, please email me (my email is included on my profile).

**Comment by johncadengo** [comment]
Hi, @josegonzalez is this still the case?

**Comment by josegonzalez** [comment]
This is still the case. See the [sponsoring](https://github.com/dokku/.github/blob/master/SPONSORING.md) doc for more information on how to sponsor new functionality.
