### ISSUE TITLE
Scheduled backups create crontabs with invalid syntax

### ISSUE THREAD

**Issue by mspanc** [dokku/dokku-postgres#95]
I have created a schedule using the following command:

`dokku postgres:backup-schedule myapp "0 4 * * *" myapp-dokku-postgresql-backup`

It has created a file `/etc/cron.d/dokku-postgres-myapp` with the following contents:

`0 dokku /usr/bin/dokku postgres:backup myapp 4`

Which has obviously invalid syntax.

**Comment by mspanc** [comment]
It happens only if I call dokku via SSH, like `ssh dokku@myhost postgres:backup-schedule myapp "0 4 * * *" myapp-dokku-postgresql-backup`. Probably something is wrong with args escaping.

For that reason it would have been better if script was interpreting each part of the cron time definition as a separate argument.

**Comment by josegonzalez** [comment]
Use single-quotes. Bash will try and expand the `*` character on the cli if its enclosed in double-quotes.

**Comment by josegonzalez** [comment]
Note: our documentation here could be improved with an example and a notice. Feel free to pull request that :)

**Comment by mspanc** [comment]
I checked that, with single quotes is the same.

**Comment by josegonzalez** [comment]
Are you issuing the request over ssh?

**Comment by mspanc** [comment]
Yes I have written that in my first comment

**Comment by josegonzalez** [comment]
Gotcha. Well I think you'd need to escape the variables over ssh. As Dokku doesn't control your local ssh, nothing we can do there.

I'd imagine that using flags for each section would also result in the same issue, as you'd still need to escape the variables. Are you thinking of some other way to do this that would be ssh compatible?

**Comment by agorf** [comment]
@josegonzalez I was also tricked by this. Would you accept a PR on the README file mentioning this?
