### ISSUE TITLE
sudo asking for password of dokku user on postgres:backup-schedule 

### ISSUE THREAD

**Issue by mspanc** [dokku/dokku-postgres#96]
When I launch such command on the dokku machine (not via SSH):

```
# dokku postgres:backup-schedule myapp "0 4 * * *" mybucket
```

it ends up on asking for password for dokku

```
[sudo] password for dokku:
```

That happens regardless if I call it as root or as dokku.

Other posgres commands work fine.

Dokku 0.8.0.

**Comment by josegonzalez** [comment]
How did you install the plugin? Did you just clone it?

**Comment by mspanc** [comment]
I have run command via ansible, but it was just `dokku plugin:install https://github.com/dokku/dokku-postgres.git postgres` as root

**Comment by josegonzalez** [comment]
Run `dokku plugin:install` as root. Sounds like the install failed somewhere for some odd reason, since we set perms properly at that phase.

**Comment by mspanc** [comment]
It is production machine, can re-install it safely with such command?

**Comment by josegonzalez** [comment]
Yes. Checkout what the `install` script does if you're scared ;)

**Comment by mspanc** [comment]
```
# dokku plugin:install https://github.com/dokku/dokku-postgres.git
-----> Cloning plugin repo https://github.com/dokku/dokku-postgres.git to /var/lib/dokku/plugins/available/postgres
fatal: destination path 'postgres' already exists and is not an empty directory.
```

If I remove it and install again, would it kill my postgres containers?

**Comment by mspanc** [comment]
Got it,

I have moved /var/lib/dokku/services/ to somewhere else to keep postgresql DB on another, larger drive, but sudoers does not permit that:

```
# cat /etc/sudoers.d/dokku-postgres
%dokku ALL=(ALL) NOPASSWD:/bin/rm -f /etc/cron.d/dokku-postgres-*
%dokku ALL=(ALL) NOPASSWD:/bin/chown root\:root /etc/cron.d/dokku-postgres-*
%dokku ALL=(ALL) NOPASSWD:/bin/mv /var/lib/dokku/services/postgres/.TMP_CRON_FILE /etc/cron.d/dokku-postgres-*
%dokku ALL=(ALL) NOPASSWD:/bin/chown 8983 /var/lib/dokku/services/postgres/*
%dokku ALL=(ALL) NOPASSWD:/bin/chgrp 8983 /var/lib/dokku/services/postgres/*
```

**Comment by sheldonnbbaker** [comment]
I'm also stuck on this error, specifically running into this as well (when trying to reinstall dokku-postgres):
`# dokku plugin:install https://github.com/dokku/dokku-postgres.git`
`fatal: destination path 'postgres' already exists and is not an empty directory. `

I'm on dokku 0.7.1 and have updated dokku-postgres to latest.

**Comment by josegonzalez** [comment]
@sheldonnbbaker you'll need to uninstall then reinstall.
